// ============================================================
//  RBSL — Data Materi
//  Edit file ini untuk menambah, mengubah, atau menghapus materi.
//  Tidak perlu menyentuh index.html sama sekali.
// ============================================================

const RBSL_CONFIG = {
  namaKomunitas: "Rumah Baca Sapu Lidi",
  tagline: "Dari kita, untuk kita.",
  deskripsi: "Perpustakaan digital bersama — tempat belajar, berbagi, dan berkarya. Seperti sapu lidi, lebih kuat bersama.",
  // Link formulir kontribusi (ganti dengan link Tally/Google Form kamu)
  linkKontribusi: "https://t.me/+p4JAxJAXuJ05OThl",
};

// ============================================================
//  TOPIK
// ============================================================
const TOPIK = [
  { id: "semua",    label: "Semua",         icon: "ti-layout-grid" },
  { id: "bitcoin",  label: "Bitcoin for Beginner", icon: "ti-currency-bitcoin" },
  { id: "bitcoinmath", label: "Bitcoin & Math", icon: "ti-math-function" },
  { id: "bitcoinphilosophy", label: "Bitcoin & Philosophy", icon: "ti-yin-yang" },
  { id: "bitcointechnicals", label: "Bitcoin Technicals Made Simple", icon: "ti-settings-cog" },
  { id: "ekonomi",  label: "Bitcoin & Economy", icon: "ti-chart-line" },
  { id: "filsafat", label: "Philosophy",       icon: "ti-brain" },
  { id: "ai",       label: "Technology", icon: "ti-cpu" },
  { id: "sejarah",  label: "Sejarah",        icon: "ti-history" },
  { id: "buku",     label: "Buku",           icon: "ti-books" },
  { id: "psikologi",label: "Psikologi",      icon: "ti-heart" },
  { id: "produktif",label: "Produktivitas",  icon: "ti-rocket" },
  { id: "bookreview", label: "Book Review",  icon: "ti-book" },
];

// ============================================================
//  MATERI
//
//  FORMAT:
//  judul       : judul materi
//  topik       : id topik dari daftar TOPIK di atas
//  jenis       : "PDF" | "Art" | "Video" | "Blog" | "Article" | "Riset" | "Podcast" | "Infographic"
//  kontributor : nama kontributor
//  tanggal     : "YYYY-MM-DD"
//  link        : link Google Drive → klik kanan file → Share → Copy link
//  thumbnail   : (opsional) link thumbnail cover
//                Format: https://drive.google.com/thumbnail?id=FILE_ID&sz=w400
//                FILE_ID = bagian /d/XXXX/ dari link Google Drive kamu
//  deskripsi   : (opsional) kalimat singkat tentang isi materi
// ============================================================
const MATERI = [
  {
    judul: "Don't Trust, Verify — Seni Membaca Kebenaran",
    topik: "bitcoinmath",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    // Ganti FILE_ID di bawah dengan ID file PDF dari Google Drive
    // Contoh link: https://drive.google.com/file/d/1aBcDeFgH.../view
    // FILE_ID = bagian setelah /d/ sampai sebelum /view
    link: "https://drive.google.com/file/d/1hycbbvCXpWt2AUXNuU4wYZqaYsOEJ7e8/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=1hycbbvCXpWt2AUXNuU4wYZqaYsOEJ7e8&sz=w400",
    deskripsi: "Semua logika, bahasa, dan seni verifikasi bermuara di tiga kata ajaib ini.",
  },
  {
    judul: "When Knowledge Becomes a Grenade",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/17HfijeWVVJ1Zy2bEQNuwvQuu0vIdV8ap/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=17HfijeWVVJ1Zy2bEQNuwvQuu0vIdV8ap&sz=w400",
    deskripsi: "Silence is the pin that holds back revolution. Educate yourself. Question everything. Bitcoin is knowledge.",
  },
  {
    judul: "Bad Sector — Time Isn't Saved, It's Spent",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.instagram.com/p/DZLoq8agXip/",
    thumbnail: "https://drive.google.com/thumbnail?id=1fTwSFlmoW4ODv2pAgR9wxo0gE-0cF0yZ&sz=w400",
    deskripsi: "Ketika sepotong hidupmu dikristalkan menjadi uang — di mana kamu menitipkan waktu itu?",
  },
  {
    judul: "Bitcoin Setelah Koin Terakhir — Apa yang Terjadi di Tahun 2140?",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=ZjNXA3kO3e0&t=80s",
    thumbnail: "https://img.youtube.com/vi/ZjNXA3kO3e0/hqdefault.jpg",
    deskripsi: "Bitcoin setelah 21 juta koin habis ditambang — apa yang terjadi dengan miner dan masa depan BTC?",
  },
  {
    judul: "Jika Surga & Neraka Tak Pernah Ada — Yakin Lo Gak Nyari Keuntungan di Bitcoin?",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=DtUwTYlWBHg",
    thumbnail: "https://img.youtube.com/vi/DtUwTYlWBHg/hqdefault.jpg",
    deskripsi: "Ngobrolin ilusi kebaikan, bitcoin, dan apa yang sebenernya kita cari. Deep talk alert!",
  },
  {
    judul: "Circular Economy @ Nusa Community Hub",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "om.sats, annasahmads, mithos_btc, bitcoinsports.id",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=IxVFvHy-uk4",
    thumbnail: "https://img.youtube.com/vi/IxVFvHy-uk4/hqdefault.jpg",
    deskripsi: "Diskusi circular economy bersama komunitas Bitcoin di Nusa Community Hub.",
  },
  {
    judul: "Puzzle of Idea",
    topik: "filsafat",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://puzzlesofidea.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1fNxHjZ24SJ5n9B5XILRGZJ1cm8W3YTmb&sz=w400",
    deskripsi: "Clarity, golden ratio, tipografi, narasi — 10 puzzle di balik setiap ide besar.",
  },
  {
    judul: "Berpikir Seperti Matematika",
    topik: "bitcoinmath",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-05-15",
    link: "https://thinklikemath.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=14UoCMU7EJdtGdR26GU9vNtRjURgNGQRO&sz=w400",
    deskripsi: "Don't Trust, Verify — belajar berpikir dengan logika dan ketelitian seperti matematika.",
  },
  {
    judul: "Kalo Satoshi Nakamoto Nongkrong di Wonderland",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/12OulA7av1--IWeC-qUMy03sTFVptvHe_/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=12OulA7av1--IWeC-qUMy03sTFVptvHe_&sz=w400",
    deskripsi: "Gimana kalo pencipta Bitcoin ketemuan sama Kucing Cheshire? Deep talk paling mind-blowing abad ini.",
  },
  {
    judul: "Ngetik Code atau Nulis Filsafat?",
    topik: "bitcoinmath",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/1lHwDtXU5iYl7UqISW7Sg--pwPNf_7FIp/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=1lHwDtXU5iYl7UqISW7Sg--pwPNf_7FIp&sz=w400",
    deskripsi: "Gimana pemikiran filsuf dari balik jeruji besi WWI jadi pondasi absolut buat Programming & Bitcoin modern.",
  },
  {
    judul: "Kripto: Harta Masa Depan atau Judi Modern?",
    topik: "ai",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-16",
    link: "https://open.spotify.com/episode/1H5nLKKXK75nu6MplSAdDo?si=OKThtg1pSzW4nZ4zpdMn_w",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a3860837bf00f4d27cf0709a8",
    deskripsi: "Kripto sah jadi harta masa depan, atau cuma judi modern berbungkus teknologi? Bedah hukum Bappebti, fatwa MUI-NU-Muhammadiyah, sampai peluang ekonomi bebas riba.",
  },
  {
    judul: "Lawan Bias Otak Agar Pensiun 35 Tahun",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-06",
    link: "https://open.spotify.com/episode/5NPa6ulhE3JtHjhCjTmT1y",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Otak kita diprogram untuk konsumtif — bedah behavioral finance, compounding, dan perbandingan emas vs Bitcoin untuk anak muda yang ingin pensiun di usia 35–40 tahun.",
  },
  {
    judul: "Bitcoin: The Public Map & The Mystery of Privacy",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-16",
    link: "https://drive.google.com/file/d/1C7SyJnohLwSmn4MWbcQsXvhRXWgf49RO/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1C7SyJnohLwSmn4MWbcQsXvhRXWgf49RO&sz=w400",
    deskripsi: "Saldo Bitcoin itu peta publik, bukan buku tabungan — gimana jejak transaksi bisa dilacak, dan cara aktifin 'stealth mode' lewat CoinJoin, Lightning Network, sampai Coin Control.",
  },
  {
    judul: "Ketika Bitcoin Bercerita — Comic Reader",
    topik: "bitcoin",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-17",
    link: "https://satoshicatstory.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1meASkmV54jPr05G8-YDHIrS27rEpDvgn&sz=w400",
    deskripsi: "Komik strip Bitcoin — kisah Satoshicat dalam 11 halaman penuh warna yang bikin paham Bitcoin tanpa perlu baca whitepaper.",
  },
  {
    judul: "Ep.1 - Celengan Pertamaku",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "achmad.ardian.syah",
    tanggal: "2026-06-17",
    link: "https://drive.google.com/file/d/14UVukXKprKyxb_fUsdmJ0tvNk9r4e55N/view?pli=1",
    thumbnail: "https://drive.google.com/thumbnail?id=14UVukXKprKyxb_fUsdmJ0tvNk9r4e55N&sz=w400",
    deskripsi: "Langkah pertama mengenal Bitcoin — dari mana mulainya, kenapa penting, dan bagaimana memulai perjalananmu sebagai pemula.",
  },
  {
    judul: "Pathfinder Strategies",
    topik: "ekonomi",
    jenis: "Blog",
    kontributor: "datul",
    tanggal: "2026-06-19",
    link: "https://pathfinderstg.com/",
    thumbnail: "https://drive.google.com/thumbnail?id=1wOLSOFE9A91x30uTwJVL9SndaONTYNf0&sz=w400",
    deskripsi: "Riset makro, strategi Bitcoin, dan liquidity intelligence — platform yang mengembangkan framework berbasis global M2 untuk trading Bitcoin secara disiplin.",
  },
  {
    judul: "Bitcoin vs Saham: Kesalahan dalam Menilai Aset",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "datul",
    tanggal: "2026-03-15",
    link: "https://hidatulfikri.substack.com/p/bitcoin-vs-saham-kesalahan-dalam",
    thumbnail: "https://substackcdn.com/image/fetch/$s_!pe0W!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F12e25483-3eaa-4cf1-847b-e04c9a049a76_677x409.png",
    deskripsi: "Mengakhiri perdebatan antara Bitcoin dan saham — membedah kesalahan umum dalam menilai dua aset yang berbeda kategori ini.",
  },
  {
    judul: "Belajar Bitcoin dari Nol dalam 10 Menit (Langsung Paham)",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "datul",
    tanggal: "2026-06-18",
    link: "https://www.youtube.com/watch?v=2tAN2gS5p9U",
    thumbnail: "https://img.youtube.com/vi/2tAN2gS5p9U/hqdefault.jpg",
    deskripsi: "Pengantar singkat Bitcoin buat pemula — paham dasar-dasarnya cuma dalam 10 menit.",
  },
  {
    judul: "Dari Nol ke Bertahan: 4 Mitos & Rahasia Hidup yang Bikin Kamu Kuat Seperti Bitcoin",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat, dhiemazalfa",
    tanggal: "2026-06-18",
    link: "https://www.youtube.com/watch?v=Oyz0gMewsUc",
    thumbnail: "https://img.youtube.com/vi/Oyz0gMewsUc/hqdefault.jpg",
    deskripsi: "Bongkar 4 mitos hidup yang bikin kita rapuh, dan gimana belajar dari ketahanan Bitcoin buat jadi lebih kuat.",
  },
  {
    judul: "Episode 3 : Adu Kedaulatan Kripto dan CBDC",
    topik: "ai",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-04",
    link: "https://open.spotify.com/episode/7hAzY9wqFhCRsab3v6Bs51",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8aebfdce052e86427dc324e1bd",
    deskripsi: "Kripto vs CBDC — benturan ideologi antara desentralisasi dan kedaulatan negara, siapa yang bakal menang kendali atas dompetmu?",
  },
  {
    judul: "Surat Terbuka: Di Antara Ketakutan Menjadi Miskin dan Kehinaan Menjadi Serakah",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-12-01",
    link: "https://www.annasahmad.com/2025/12/surat-terbuka-di-antara-ketakutan.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjAK39FrJmMqoB_3fG4JE5bTboskOhEO9oCrbzQZuQ9Tf23bYbQ2VdRZxG-hfD8Sncy0OYTUbwGXU0By-2ZSnHvnohoK4DsFFWBvY0_ehrVIX_b7MccxM6-MrdVwLw7L_gXlL_5R-mdtr0t9gd5BbMGldslw0bSlRzC0-d8mf3GY1mDy3UiWKeLNb1YCZw/w640-h430/7ef4d16d-260f-40f0-8dc7-2d0abc05f2a9.png",
    deskripsi: "Renungan tentang ketakutan mati miskin versus kehinaan mati serakah — mendefinisikan ulang makna kekayaan menjelang 2026.",
  },
  {
    judul: "Memahami Protokol Bitcoin Dengan Mudah Untuk Semua Orang",
    topik: "bitcointechnicals",
    jenis: "Blog",
    kontributor: "maxima.freiman",
    tanggal: "2026-06-18",
    link: "https://bitprotocol.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1ndtAZtj3EUe33FQjuRviPcs80BSCJrtK&sz=w400",
    deskripsi: "Pelajari bagaimana Bitcoin bekerja dari dasar hingga mekanisme terdalamnya, tanpa jargon rumit, tanpa hype crypto, dan tanpa harus jadi programmer.",
  },
  {
    judul: "3 Mitos dan 2 Angka yang Perlu Kamu Cari",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-02-01",
    link: "https://www.annasahmad.com/2025/02/3-mitos-dan-2-angka-yang-perlu-kamu.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjjRtu9swKmFgXHpyk3ooRe3wzq8ngCbgrcJzDjPxyxiKkj8SgSkBhZIkxNqr5HPCliFnk74HQrS2gNSMFnjSkq7Z3LtlP0Ohp7du9QzcTM40yABtZNsmyER99uW63iJ4zqVSPw8dgIbCVZdl1WG6HJjbtflwS0FSUl_6POYeyXB4CNM3yk_Hqa-44qNMk/s1312/k2sWc8g2Ssun28-CXuNr8A.webp",
    deskripsi: "Membongkar mitos-mitos seputar keuangan dan dua angka penting yang sering diabaikan, tapi sebenarnya krusial untuk perjalanan finansialmu.",
  },
  {
    judul: "Karet Nasi Padang",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-18",
    link: "https://www.instagram.com/p/DOV2C66DxN4/",
    thumbnail: "https://drive.google.com/thumbnail?id=1AJN7GDwsfFatkAlTax_TWnOcufMD7Pjg&sz=w400",
    deskripsi: "Kecil, murah, kadang putus — tapi selalu ada saat dibutuhkan. Refleksi tentang peran-peran yang dianggap remeh tapi menahan segalanya tetap utuh.",
  },
  {
    judul: "Siapa sih yang Pertama Kali Ngadain Makan 3x Sehari?",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-04-16",
    link: "https://jokowarihwiguna.blogspot.com/2026/04/makan-3x-sehari-siapa-yang-ciptakan.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1ivXxipeLwDR0tvyn5oSJiWkf8g_LhHPZ&sz=w400",
    deskripsi: "Hal yang dianggap biasa, dibedah sampai dalam — menelusuri asal-usul kebiasaan makan tiga kali sehari yang jarang dipertanyakan.",
  },
  {
    judul: "Berapa Bitcoin yang \"Cukup\"?",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-06-18",
    link: "https://drive.google.com/open?id=1cdD9DE3SNMtwGL84WaMLkLnlYPmb8Ikm",
    thumbnail: "https://drive.google.com/thumbnail?id=1cdD9DE3SNMtwGL84WaMLkLnlYPmb8Ikm&sz=w400",
    deskripsi: "Target 1 BTC vs 0,1 BTC — kenapa 0,1 BTC sudah menempatkanmu jauh di atas mayoritas populasi dunia, dan mengapa Bitcoin lebih baik dijadikan aset warisan lintas generasi.",
  },
  {
    judul: "The Richest Man in Babylon — Ringkasan & Penerapannya di 2026",
    topik: "bookreview",
    jenis: "PDF",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-03-01",
    link: "https://drive.google.com/file/d/1vIJr1dYnXO6d_ubpitl6dwS3oB-xOVZb/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1vIJr1dYnXO6d_ubpitl6dwS3oB-xOVZb&sz=w400",
    deskripsi: "Ringkasan buku klasik karya George S. Clason beserta penerapan praktisnya di Indonesia 2026 — dari 7 prinsip membangun kekayaan hingga simulasi DCA Bitcoin.",
  },
  {
    judul: "Understanding Bitcoin: A 21-Day Tweet-a-Day Journey (Bahasa Indonesia)",
    topik: "bookreview",
    jenis: "PDF",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-06-18",
    link: "https://drive.google.com/file/d/1FKvjyDGumFN4nVoofTkMgS9OUCgX4MEk/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1FKvjyDGumFN4nVoofTkMgS9OUCgX4MEk&sz=w400",
    deskripsi: "Panduan Bitcoin 22 topik dalam Bahasa Indonesia — dari \"Apa itu Bitcoin?\" sampai membongkar mitos-mitos seperti soal energi, kriminalitas, dan larangan pemerintah. Cocok untuk pemula.",
  },
  {
    judul: "Thailand: Pasar Jimat Terbesar",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-19",
    link: "https://www.facebook.com/1216429964/posts/pfbid02wSPsaZtHuXX1p2VMjm99rj7SmRxY8cFn93QoAcmWgnXB6fYSmroQgNCbeqSBSyc6l/",
    thumbnail: "https://drive.google.com/thumbnail?id=1f1Yzh7h0Z7XrjAuaRNgxvp7_FpYLsjsy&sz=w400",
    deskripsi: "Cerita dari pasar jimat terbesar di Thailand — renungan soal kepercayaan, keberuntungan, dan apa yang sebenarnya orang cari lewat benda-benda semacam ini.",
  },
  {
    judul: "Episode 4 - Bitcoin White Paper: Sistem Keuangan Bitcoin Tanpa Perantara Bank",
    topik: "bitcoin",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-05",
    link: "https://open.spotify.com/episode/64XtEEHWugQbQqvHfWztvg",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8aeac1e37041a7de8e83709a19",
    deskripsi: "Membedah Bitcoin White Paper karya Satoshi Nakamoto — gimana sistem peer-to-peer ini menyelesaikan masalah double-spending tanpa butuh bank sebagai perantara.",
  },
  {
    judul: "Sunyi Licik",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DOdr8lxjw7C/",
    thumbnail: "https://drive.google.com/thumbnail?id=18K44QY0tyKI0KYLsVE-UF71glmAI1_nM&sz=w400",
    deskripsi: "Puisi singkat tentang kesunyian yang licik — kadang duduk di kursi, kadang merayap di pemandangan, membuat kita percaya ia sudah pergi.",
  },
  {
    judul: "Bitcoin Gagal Jadi Uang?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "annasahmads, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1L__fYs4fjDcgE1cv-mNoh3Zf8QeO1QXF/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1L__fYs4fjDcgE1cv-mNoh3Zf8QeO1QXF&sz=w400",
    deskripsi: "Menelusuri kenapa Bitcoin dianggap belum berhasil jadi uang dalam arti penuh, dan apa makna sebenarnya di balik fungsi uang itu sendiri.",
  },
  {
    judul: "Bitcoin with Awareness",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "bitcoinsports.id, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1AIIantk_qeFkhR2cMDQQEp3yipqg4LV4/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1AIIantk_qeFkhR2cMDQQEp3yipqg4LV4&sz=w400",
    deskripsi: "Memahami Bitcoin bukan sekadar dari sisi teknis, tapi dengan kesadaran penuh — apa makna kepemilikan, kebebasan, dan tanggung jawab di baliknya.",
  },
  {
    judul: "The Offline Node: Kenapa Bitcoin dan Agama Punya Satu Rahasia yang Sama",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1THfa45YpwsCxMlMgR_82MCSfIUSUsze0/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1THfa45YpwsCxMlMgR_82MCSfIUSUsze0&sz=w400",
    deskripsi: "Menggali kesamaan tak terduga antara Bitcoin dan agama — keduanya bertumpu pada satu rahasia yang sama: keyakinan tanpa perlu otoritas pusat.",
  },
  {
    judul: "Bitcoin Script: Bahasa Rahasia di Balik Uang Kita",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1HI6rw4YoSy3WP2FgJnYpEgnDjqavDTMG/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1HI6rw4YoSy3WP2FgJnYpEgnDjqavDTMG&sz=w400",
    deskripsi: "Bukan sekadar kode, ini adalah mantra yang menjaga triliunan dolar aset dunia — membongkar bahasa rahasia di balik Bitcoin Script.",
  },
  {
    judul: "Kartini & Bitcoin (sebuah obrolan santai tentang kasta, kebebasan dan feodalisme yang ganti skin)",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1LWH59Cn5CoM4mEn0-uwhPZD-Rm4dgSOq/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1LWH59Cn5CoM4mEn0-uwhPZD-Rm4dgSOq&sz=w400",
    deskripsi: "Obrolan santai tentang kasta, kebebasan, dan feodalisme yang ganti skin — menghubungkan semangat Kartini dengan perjuangan kebebasan finansial lewat Bitcoin.",
  },
  {
    judul: "Bitcoin Realistis: Panduan Waras di Dunia Gila (sebuah obrolan santai buat kita yang mau investasi tanpa kehilangan akal sehat)",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "annasahmads, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/10__hUqIFFrYkHV1Luy3FLfUuffUNjrjs/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=10__hUqIFFrYkHV1Luy3FLfUuffUNjrjs&sz=w400",
    deskripsi: "Obrolan santai buat kita yang mau investasi Bitcoin tanpa kehilangan akal sehat — panduan waras di tengah euforia dan kepanikan dunia kripto.",
  },
  {
    judul: "UTXO: Lu Pikir Bitcoin Kayak Saldo GoPay? Salah Besar, Bro!",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1GR7L30dRNfy9fPU1-bJfRPbvuae88nHD/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1GR7L30dRNfy9fPU1-bJfRPbvuae88nHD&sz=w400",
    deskripsi: "Di kepala kita, uang itu angka 'balance' yang cair. Tapi di Bitcoin nggak ada yang namanya saldo — kenalan sama konsep UTXO yang sebenarnya.",
  },
  {
    judul: "Soledad, Bitcoin, Winter Solstice & Old Soul",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "theuniverseismycampus, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.youtube.com/watch?v=euvf-LuPbyE",
    thumbnail: "https://img.youtube.com/vi/euvf-LuPbyE/hqdefault.jpg",
    deskripsi: "Refleksi tentang kesendirian, Bitcoin, titik balik musim dingin, dan jiwa yang tua — sebuah perenungan filosofis yang menghubungkan alam, waktu, dan Bitcoin.",
  },
  {
    judul: "Hamlet, Telur Dadar, Bitcoin | Filosofi Hidup yang Mengubah Cara Berpikir",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "theuniverseismycampus, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.youtube.com/watch?v=ln12U4i3kOs&t=135s",
    thumbnail: "https://img.youtube.com/vi/ln12U4i3kOs/hqdefault.jpg",
    deskripsi: "Dari dilema Hamlet sampai cara masak telur dadar — sebuah perjalanan filosofis yang mengubah cara berpikir tentang hidup dan Bitcoin.",
  },
  {
    judul: "Kalkulator DCA Bitcoin V3.0",
    topik: "bitcoin",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/p/kalkulator-dca-bitcoin-v30.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1DvjdJhgJsRYUzzWBYb4Y38u_kcIZ9_GW&sz=w400",
    deskripsi: "Alat bantu hitung simulasi Dollar Cost Averaging (DCA) Bitcoin — lihat potensi hasil investasi rutinmu dari waktu ke waktu.",
  },
  {
    judul: "AngkaCukup",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/p/angkacukup.html",
    thumbnail: "https://drive.google.com/thumbnail?id=19JC2FasckzlaOjAVoyBpRrMxgsLkRH9t&sz=w400",
    deskripsi: "Alat bantu menghitung 'angka cukup' kamu — berapa sebenarnya yang kamu butuhkan untuk merasa cukup secara finansial.",
  },
  {
    judul: "Kelakuan Trader: Menjelaskan Bitcoin",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DGw7rkPp6ed/",
    thumbnail: "https://drive.google.com/thumbnail?id=1bihgkzVOrgJj88omuqsipreBeikF7Qbb&sz=w400",
    deskripsi: "Potret jenaka tingkah laku trader saat mencoba menjelaskan Bitcoin — relate banget buat yang sering ngobrolin crypto sama orang awam.",
  },
  {
    judul: "Kelakuan Trader: Halving Kok Gini",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/C6Ag1-rpVfa/",
    thumbnail: "https://drive.google.com/thumbnail?id=135ttUr1KgGSQjhqEazqBb4aFfctjqUK7&sz=w400",
    deskripsi: "Reaksi trader menghadapi momen halving Bitcoin yang gak sesuai ekspektasi — santai tapi mengena.",
  },
  {
    judul: "Kaleng Kosong",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DOny5aED6kS/",
    thumbnail: "https://drive.google.com/thumbnail?id=1BkFMdtNxXnsUCIXFu8VBLd8RMyyXyhRu&sz=w400",
    deskripsi: "Setiap diinjak, ia berbunyi lebih keras — daripada orang penuh isi yang takut bersuara. Puisi singkat tentang kebisingan kosong versus kebijaksanaan yang diam.",
  },
  {
    judul: "Episode 5 - Sejarah Rupiah dari Nyawa ke Digital",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-05",
    link: "https://open.spotify.com/episode/7hOiJ9j9leb6c4F3EZcQP4",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Uang bukan sekadar alat berbelanja, tapi simbol kedaulatan dan saksi bisu jatuh bangunnya bangsa — menyelami perjalanan panjang mata uang Rupiah dengan bahasa yang santai dan penuh insight.",
  },
  {
    judul: "Cara Hidup \"In This Economy\" (Juni 2026) - Happy Ikigai",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/2026/06/cara-hidup-in-this-economy-juni-2026.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjf368lq-BedJepVu-WLXKgoHUysKbEr4HYa6eXnXMgjwwOjkVz42LgXs77r5i4nJ-CRZXXMrqjE25aIyTnUfAVqamnK2u0Tzf3gLMDKyT3zuRc759EdJd2xmYv8RZxtY3ChAsCRCnxwpHfjC7ByFN2YShy2v9P9A1L82zh-8sULrP9eddk0PLoWNKgESQ/s1168/2026a.jpg",
    deskripsi: "Tips bertahan dan tetap waras menjalani hidup di tengah tekanan ekonomi 'in this economy' versi Juni 2026 — ala Happy Ikigai.",
  },
  {
    judul: "Emas vs. Bitcoin: Peter Schiff X CZ - Happy Ikigai",
    topik: "bitcoin",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-12-01",
    link: "https://www.annasahmad.com/2025/12/emas-vs-bitcoin-peter-schiff-cz.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJQLPxJH9y-2lEn1YHeAs5LjHG_-eaHy5gll8Z5QaNwGjbTpGQ2Ar1OHCYtr4tNuk-SBh1K_eaTIOYqqf-ozAWnRe4QA2Maz_uwlmxKvzNAMa3JQds0kdd1ZwuxLD2sgQ2ciM6tCYUSN41L6Oqn1k4Or94LUM6hxWfPvahtgIgNLyvRWize_v7eTvwHqo/s1024/unnamed%20(54).jpg",
    deskripsi: "Adu pandangan klasik soal emas vs Bitcoin lewat perdebatan Peter Schiff dan CZ — cocok buat yang baru mulai belajar Bitcoin.",
  },
  {
    judul: "The Art of Secrets — Seni Melindungi Apa yang Paling Lu Cintai",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ZZjvUjYyEizikEqcjYNGhcVh03nv4uVx/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ZZjvUjYyEizikEqcjYNGhcVh03nv4uVx&sz=w400",
    deskripsi: "Ngobrolin kriptografi, blockchain, dan kenapa internet belum kiamat.",
  },
  {
    judul: "Seberapa Gila Keamanan 256-Bit?",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ijEzZqLeR3MR_WSOI9jAKWmGYaKHgXu3/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ijEzZqLeR3MR_WSOI9jAKWmGYaKHgXu3&sz=w400",
    deskripsi: "Kenapa sistem sekelas Bitcoin nyaris mustahil ditembus? Zoom-out dari sebuah kotak kecil sampai ke ujung tata surya.",
  },
  {
    judul: "Standar Siapa? — Editorial",
    topik: "bitcoinphilosophy",
    jenis: "Article",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://standarsiapa.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1owvtWe9YI2z8KOJb-GL0SVu_Fn4qX-x8&sz=w400",
    deskripsi: "Mempertanyakan standar yang selama ini dianggap baku — siapa yang sebenarnya menentukan ukuran 'normal', 'benar', dan 'bernilai' dalam hidup kita?",
  },
  {
    judul: "From Banking to Bitcoin",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1JaIcQkEJusDLScdZX3QHxa7JUMOcnscV/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1JaIcQkEJusDLScdZX3QHxa7JUMOcnscV&sz=w400",
    deskripsi: "Sebuah kisah transisi, keyakinan, dan membangun masa depan — dari mengelola uang, memahami uang, hingga membangun ulang sistem uang lewat Bitcoin.",
  },
  {
    judul: "DHIPA21 — Kepulauan & Pelita",
    topik: "bitcoin",
    jenis: "Blog",
    kontributor: "AH Prayo, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://dhipa21.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1rxIgyylv1zpo9mlmVbGDGC-59BZLThR2&sz=w400",
    deskripsi: "Zine independen untuk mereka yang percaya uang yang baik bisa mengubah peradaban — Bitcoin sebagai pelita baru dari kepulauan Nusantara, untuk dunia.",
  },
  {
    judul: "Mengubah Keyakinan",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2022-08-01",
    link: "https://www.annasahmad.com/2022/08/mengubah-keyakinan.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgh328chW1MKgaQLQT-GT6QU3u0VbVosGbjO8NqU9zO4LSRBEJ7a_DebHm_RFn-buDn-UN5IFPXcVL4UF_dBPALBcum06OVI0DnQck4c65RRSbLe4rbnt58EBVFiCj0OORQA6uTOw2tZEMIdO3qbmygGLKofi5eI8bhL2NkH0MXHzXm_Sf1UjTg1dt9/s1080/zonaperubahan.png",
    deskripsi: "Mengubah keyakinan bukan perkara mudah — sebuah renungan tentang bagaimana cara pandang kita terhadap dunia bisa membuka atau menutup pintu perubahan.",
  },
  {
    judul: "Episode 6 - Rahasia Penciptaan Uang dari Pulau Jekyll",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Podcast Kurniawan",
    tanggal: "2026-06-06",
    link: "https://open.spotify.com/episode/4QZ814xjbdVaAysQjNWLS0",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Bongkar konspirasi Pulau Jekyll — pertemuan rahasia para bankir elit tahun 1910 yang melahirkan Federal Reserve dan mengubah cara dunia mencetak uang.",
  },
  {
    judul: "Sejarah Rupiah",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2025-11-28",
    link: "https://docs.google.com/presentation/d/1NeIfSvt4T4LqPdb_I02mzr6zC8oeAZyVYzMIylEWuVk/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ewPsMWUFM2qAd5kX6sJI8g7UtOwNzCmy&sz=w400",
    deskripsi: "Menelusuri perjalanan sejarah mata uang Rupiah dari masa ke masa — dibawakan dalam Bitcoin Indonesia Online Meetup.",
  },
  {
    judul: "They Didn't Protest, They Encrypted",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQk6devgZS6/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1BiSe7DN1dw8_jEg_RWXJ5xULY9bkNET-&sz=w400",
    deskripsi: "Mereka tidak berdemonstrasi, mereka mengenkripsi — sebuah ilustrasi yang merujuk pada A Cypherpunk's Manifesto: privasi adalah kebutuhan untuk masyarakat terbuka di era digital.",
  },
  {
    judul: "Sejarah Uang",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2025-10-26",
    link: "https://docs.google.com/presentation/d/1TKnOptiwxhV-DZyLW09GvukUdJdP1WANxKUv8-b8CgM/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1AHVFCC3gbcbionL8_k9uPXoFsNipmQ51&sz=w400",
    deskripsi: "Menelusuri perjalanan sejarah uang dari masa ke masa — dibawakan dalam komunitas Bitcoin Indonesia di Jakarta Barat.",
  },
  {
    judul: "Coffee for Value",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQGcYOjCmox/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1HGP4AMNQH42mt-jcWbUvtnxeHd6VonOj&sz=w400",
    deskripsi: "Tukar kopi dengan Bitcoin — sebuah ilustrasi sederhana tentang nilai, kepercayaan, dan pertukaran yang adil antara dua tangan dari dunia yang berbeda.",
  },
  {
    judul: "Before Money Was Printed, It Was Proof of Work",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQGA7PZDDqw/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1ruWXG_CK7jzATPbqjiumTWrv1N4OkVyX&sz=w400",
    deskripsi: "Sebelum uang dicetak, ia adalah bukti kerja — ilustrasi yang menghubungkan konsep barter purba dengan Proof of Work yang menjadi fondasi Bitcoin hari ini.",
  },


];
