// ============================================================
//  RBSL — Data Materi
//  Edit file ini untuk menambah, mengubah, atau menghapus materi.
//  Tidak perlu menyentuh index.html sama sekali.
// ============================================================

const RBSL_CONFIG = {
  namaKomunitas: "Rumah Baca Sapu Lidi",
  tagline: "Dari kita, untuk kita.",
  deskripsi: "Perpustakaan digital bersama — tempat belajar, berbagi, dan berkarya. Seperti sapu lidi, lebih kuat bersama.",
  // Link formulir kontribusi (ganti dengan link Tally/Google Form kamu)
  linkKontribusi: "https://forms.gle/qnPkcKaLX41VnAzd6",
};

// ============================================================
//  TOPIK
// ============================================================
const TOPIK = [
  { id: "semua",    label: "Semua",         icon: "ti-layout-grid" },
  { id: "bitcoin",  label: "Bitcoin for Beginner", icon: "ti-currency-bitcoin" },
  { id: "bitcoinmath", label: "Bitcoin & Math", icon: "ti-math-function" },
  { id: "bitcoinphilosophy", label: "Bitcoin & Philosophy", icon: "ti-yin-yang" },
  { id: "bitcointechnicals", label: "Bitcoin Technicals Made Simple", icon: "ti-settings-cog" },
  { id: "ekonomi",  label: "Bitcoin & Economy", icon: "ti-chart-line" },
  { id: "bitcoin-kids", label: "Bitcoin for Kids", icon: "ti-mood-kid" },
  { id: "bitcoin-grandparents", label: "Bitcoin for Grandparents", icon: "ti-hearts" },
  { id: "technicalanalysis", label: "Technical Analysis", icon: "ti-chart-candle" },
  { id: "sapulidijournal", label: "Sapu Lidi's Journal", icon: "ti-feather" },
  { id: "filsafat", label: "Philosophy",       icon: "ti-brain" },
  { id: "ai",       label: "Technology", icon: "ti-cpu" },
  { id: "sejarah",  label: "Sejarah",        icon: "ti-history" },
  { id: "buku",     label: "Buku",           icon: "ti-books" },
  { id: "psikologi",label: "Psikologi",      icon: "ti-heart" },
  { id: "produktif",label: "Produktivitas",  icon: "ti-rocket" },
  { id: "bookreview", label: "Book Review",  icon: "ti-book" },
];

// ============================================================
//  MATERI
//
//  FORMAT:
//  judul       : judul materi
//  topik       : id topik dari daftar TOPIK di atas
//  jenis       : "PDF" | "Art" | "Video" | "Blog" | "Article" | "Riset" | "Podcast" | "Infographic"
//  kontributor : nama kontributor
//  tanggal     : "YYYY-MM-DD"
//  link        : link Google Drive → klik kanan file → Share → Copy link
//  thumbnail   : (opsional) link thumbnail cover
//                Format: https://drive.google.com/thumbnail?id=FILE_ID&sz=w400
//                FILE_ID = bagian /d/XXXX/ dari link Google Drive kamu
//  deskripsi   : (opsional) kalimat singkat tentang isi materi
// ============================================================
const MATERI = [
  {
    judul: "Don't Trust, Verify — Seni Membaca Kebenaran",
    topik: "bitcoinmath",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    // Ganti FILE_ID di bawah dengan ID file PDF dari Google Drive
    // Contoh link: https://drive.google.com/file/d/1aBcDeFgH.../view
    // FILE_ID = bagian setelah /d/ sampai sebelum /view
    link: "https://drive.google.com/file/d/1hycbbvCXpWt2AUXNuU4wYZqaYsOEJ7e8/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=1hycbbvCXpWt2AUXNuU4wYZqaYsOEJ7e8&sz=w400",
    deskripsi: "Semua logika, bahasa, dan seni verifikasi bermuara di tiga kata ajaib ini.",
  },
  {
    judul: "When Knowledge Becomes a Grenade",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/17HfijeWVVJ1Zy2bEQNuwvQuu0vIdV8ap/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=17HfijeWVVJ1Zy2bEQNuwvQuu0vIdV8ap&sz=w400",
    deskripsi: "Silence is the pin that holds back revolution. Educate yourself. Question everything. Bitcoin is knowledge.",
  },
  {
    judul: "Bad Sector — Time Isn't Saved, It's Spent",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.instagram.com/p/DZLoq8agXip/",
    thumbnail: "https://drive.google.com/thumbnail?id=1fTwSFlmoW4ODv2pAgR9wxo0gE-0cF0yZ&sz=w400",
    deskripsi: "Ketika sepotong hidupmu dikristalkan menjadi uang — di mana kamu menitipkan waktu itu?",
  },
  {
    judul: "Bitcoin Setelah Koin Terakhir — Apa yang Terjadi di Tahun 2140?",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=ZjNXA3kO3e0&t=80s",
    thumbnail: "https://img.youtube.com/vi/ZjNXA3kO3e0/hqdefault.jpg",
    deskripsi: "Bitcoin setelah 21 juta koin habis ditambang — apa yang terjadi dengan miner dan masa depan BTC?",
  },
  {
    judul: "Jika Surga & Neraka Tak Pernah Ada — Yakin Lo Gak Nyari Keuntungan di Bitcoin?",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=DtUwTYlWBHg",
    thumbnail: "https://img.youtube.com/vi/DtUwTYlWBHg/hqdefault.jpg",
    deskripsi: "Ngobrolin ilusi kebaikan, bitcoin, dan apa yang sebenernya kita cari. Deep talk alert!",
  },
  {
    judul: "Circular Economy @ Nusa Community Hub",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "om.sats, annasahmads, mithos_btc, bitcoinsports.id",
    tanggal: "2025-06-16",
    link: "https://www.youtube.com/watch?v=IxVFvHy-uk4",
    thumbnail: "https://img.youtube.com/vi/IxVFvHy-uk4/hqdefault.jpg",
    deskripsi: "Diskusi circular economy bersama komunitas Bitcoin di Nusa Community Hub.",
  },
  {
    judul: "Puzzle of Idea",
    topik: "filsafat",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://puzzlesofidea.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1fNxHjZ24SJ5n9B5XILRGZJ1cm8W3YTmb&sz=w400",
    deskripsi: "Clarity, golden ratio, tipografi, narasi — 10 puzzle di balik setiap ide besar.",
  },
  {
    judul: "Berpikir Seperti Matematika",
    topik: "bitcoinmath",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-05-15",
    link: "https://thinklikemath.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=14UoCMU7EJdtGdR26GU9vNtRjURgNGQRO&sz=w400",
    deskripsi: "Don't Trust, Verify — belajar berpikir dengan logika dan ketelitian seperti matematika.",
  },
  {
    judul: "Kalo Satoshi Nakamoto Nongkrong di Wonderland",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/12OulA7av1--IWeC-qUMy03sTFVptvHe_/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=12OulA7av1--IWeC-qUMy03sTFVptvHe_&sz=w400",
    deskripsi: "Gimana kalo pencipta Bitcoin ketemuan sama Kucing Cheshire? Deep talk paling mind-blowing abad ini.",
  },
  {
    judul: "Ngetik Code atau Nulis Filsafat?",
    topik: "bitcoinmath",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2025-06-16",
    link: "https://drive.google.com/file/d/1lHwDtXU5iYl7UqISW7Sg--pwPNf_7FIp/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=1lHwDtXU5iYl7UqISW7Sg--pwPNf_7FIp&sz=w400",
    deskripsi: "Gimana pemikiran filsuf dari balik jeruji besi WWI jadi pondasi absolut buat Programming & Bitcoin modern.",
  },
  {
    judul: "Episode 2: Kripto: Harta Masa Depan atau Judi Modern?",
    topik: "ai",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-16",
    link: "https://open.spotify.com/episode/1H5nLKKXK75nu6MplSAdDo?si=OKThtg1pSzW4nZ4zpdMn_w",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a3860837bf00f4d27cf0709a8",
    deskripsi: "Kripto sah jadi harta masa depan, atau cuma judi modern berbungkus teknologi? Bedah hukum Bappebti, fatwa MUI-NU-Muhammadiyah, sampai peluang ekonomi bebas riba.",
  },
  {
    judul: "Episode 7: Lawan Bias Otak Agar Pensiun 35 Tahun",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-06",
    link: "https://open.spotify.com/episode/5NPa6ulhE3JtHjhCjTmT1y",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Otak kita diprogram untuk konsumtif — bedah behavioral finance, compounding, dan perbandingan emas vs Bitcoin untuk anak muda yang ingin pensiun di usia 35–40 tahun.",
  },
  {
    judul: "Bitcoin: The Public Map & The Mystery of Privacy",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-16",
    link: "https://drive.google.com/file/d/1C7SyJnohLwSmn4MWbcQsXvhRXWgf49RO/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1C7SyJnohLwSmn4MWbcQsXvhRXWgf49RO&sz=w400",
    deskripsi: "Saldo Bitcoin itu peta publik, bukan buku tabungan — gimana jejak transaksi bisa dilacak, dan cara aktifin 'stealth mode' lewat CoinJoin, Lightning Network, sampai Coin Control.",
  },
  {
    judul: "Ketika Bitcoin Bercerita — Comic Reader",
    topik: "bitcoin",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-17",
    link: "https://satoshicatstory.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1meASkmV54jPr05G8-YDHIrS27rEpDvgn&sz=w400",
    deskripsi: "Komik strip Bitcoin — kisah Satoshicat dalam 11 halaman penuh warna yang bikin paham Bitcoin tanpa perlu baca whitepaper.",
  },
  {
    judul: "Ep.1 - Celengan Pertamaku",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "achmad.ardian.syah",
    tanggal: "2026-06-17",
    link: "https://drive.google.com/file/d/14UVukXKprKyxb_fUsdmJ0tvNk9r4e55N/view?pli=1",
    thumbnail: "https://drive.google.com/thumbnail?id=14UVukXKprKyxb_fUsdmJ0tvNk9r4e55N&sz=w400",
    deskripsi: "Langkah pertama mengenal Bitcoin — dari mana mulainya, kenapa penting, dan bagaimana memulai perjalananmu sebagai pemula.",
  },
  {
    judul: "Pathfinder Strategies",
    topik: "ekonomi",
    jenis: "Blog",
    kontributor: "datul",
    tanggal: "2026-06-19",
    link: "https://pathfinderstg.com/",
    thumbnail: "https://drive.google.com/thumbnail?id=1wOLSOFE9A91x30uTwJVL9SndaONTYNf0&sz=w400",
    deskripsi: "Riset makro, strategi Bitcoin, dan liquidity intelligence — platform yang mengembangkan framework berbasis global M2 untuk trading Bitcoin secara disiplin.",
  },
  {
    judul: "Bitcoin vs Saham: Kesalahan dalam Menilai Aset",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "datul",
    tanggal: "2026-03-15",
    link: "https://hidatulfikri.substack.com/p/bitcoin-vs-saham-kesalahan-dalam",
    thumbnail: "https://substackcdn.com/image/fetch/$s_!pe0W!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F12e25483-3eaa-4cf1-847b-e04c9a049a76_677x409.png",
    deskripsi: "Mengakhiri perdebatan antara Bitcoin dan saham — membedah kesalahan umum dalam menilai dua aset yang berbeda kategori ini.",
  },
  {
    judul: "Belajar Bitcoin dari Nol dalam 10 Menit (Langsung Paham)",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "datul",
    tanggal: "2026-06-18",
    link: "https://www.youtube.com/watch?v=2tAN2gS5p9U",
    thumbnail: "https://img.youtube.com/vi/2tAN2gS5p9U/hqdefault.jpg",
    deskripsi: "Pengantar singkat Bitcoin buat pemula — paham dasar-dasarnya cuma dalam 10 menit.",
  },
  {
    judul: "Dari Nol ke Bertahan: 4 Mitos & Rahasia Hidup yang Bikin Kamu Kuat Seperti Bitcoin",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "Bitcoin SatoshiCat, dhiemazalfa",
    tanggal: "2026-06-18",
    link: "https://www.youtube.com/watch?v=Oyz0gMewsUc",
    thumbnail: "https://img.youtube.com/vi/Oyz0gMewsUc/hqdefault.jpg",
    deskripsi: "Bongkar 4 mitos hidup yang bikin kita rapuh, dan gimana belajar dari ketahanan Bitcoin buat jadi lebih kuat.",
  },
  {
    judul: "Episode 3 : Adu Kedaulatan Kripto dan CBDC",
    topik: "ai",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-04",
    link: "https://open.spotify.com/episode/7hAzY9wqFhCRsab3v6Bs51",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8aebfdce052e86427dc324e1bd",
    deskripsi: "Kripto vs CBDC — benturan ideologi antara desentralisasi dan kedaulatan negara, siapa yang bakal menang kendali atas dompetmu?",
  },
  {
    judul: "Surat Terbuka: Di Antara Ketakutan Menjadi Miskin dan Kehinaan Menjadi Serakah",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-12-01",
    link: "https://www.annasahmad.com/2025/12/surat-terbuka-di-antara-ketakutan.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjAK39FrJmMqoB_3fG4JE5bTboskOhEO9oCrbzQZuQ9Tf23bYbQ2VdRZxG-hfD8Sncy0OYTUbwGXU0By-2ZSnHvnohoK4DsFFWBvY0_ehrVIX_b7MccxM6-MrdVwLw7L_gXlL_5R-mdtr0t9gd5BbMGldslw0bSlRzC0-d8mf3GY1mDy3UiWKeLNb1YCZw/w640-h430/7ef4d16d-260f-40f0-8dc7-2d0abc05f2a9.png",
    deskripsi: "Renungan tentang ketakutan mati miskin versus kehinaan mati serakah — mendefinisikan ulang makna kekayaan menjelang 2026.",
  },
  {
    judul: "Memahami Protokol Bitcoin Dengan Mudah Untuk Semua Orang",
    topik: "bitcointechnicals",
    jenis: "Blog",
    kontributor: "maxima.freiman",
    tanggal: "2026-06-18",
    link: "https://bitprotocol.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1ndtAZtj3EUe33FQjuRviPcs80BSCJrtK&sz=w400",
    deskripsi: "Pelajari bagaimana Bitcoin bekerja dari dasar hingga mekanisme terdalamnya, tanpa jargon rumit, tanpa hype crypto, dan tanpa harus jadi programmer.",
  },
  {
    judul: "3 Mitos dan 2 Angka yang Perlu Kamu Cari",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-02-01",
    link: "https://www.annasahmad.com/2025/02/3-mitos-dan-2-angka-yang-perlu-kamu.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjjRtu9swKmFgXHpyk3ooRe3wzq8ngCbgrcJzDjPxyxiKkj8SgSkBhZIkxNqr5HPCliFnk74HQrS2gNSMFnjSkq7Z3LtlP0Ohp7du9QzcTM40yABtZNsmyER99uW63iJ4zqVSPw8dgIbCVZdl1WG6HJjbtflwS0FSUl_6POYeyXB4CNM3yk_Hqa-44qNMk/s1312/k2sWc8g2Ssun28-CXuNr8A.webp",
    deskripsi: "Membongkar mitos-mitos seputar keuangan dan dua angka penting yang sering diabaikan, tapi sebenarnya krusial untuk perjalanan finansialmu.",
  },
  {
    judul: "Karet Nasi Padang",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-18",
    link: "https://www.instagram.com/p/DOV2C66DxN4/",
    thumbnail: "https://drive.google.com/thumbnail?id=1AJN7GDwsfFatkAlTax_TWnOcufMD7Pjg&sz=w400",
    deskripsi: "Kecil, murah, kadang putus — tapi selalu ada saat dibutuhkan. Refleksi tentang peran-peran yang dianggap remeh tapi menahan segalanya tetap utuh.",
  },
  {
    judul: "Siapa sih yang Pertama Kali Ngadain Makan 3x Sehari?",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-04-16",
    link: "https://jokowarihwiguna.blogspot.com/2026/04/makan-3x-sehari-siapa-yang-ciptakan.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1ivXxipeLwDR0tvyn5oSJiWkf8g_LhHPZ&sz=w400",
    deskripsi: "Hal yang dianggap biasa, dibedah sampai dalam — menelusuri asal-usul kebiasaan makan tiga kali sehari yang jarang dipertanyakan.",
  },
  {
    judul: "Berapa Bitcoin yang \"Cukup\"?",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-06-18",
    link: "https://drive.google.com/open?id=1cdD9DE3SNMtwGL84WaMLkLnlYPmb8Ikm",
    thumbnail: "https://drive.google.com/thumbnail?id=1cdD9DE3SNMtwGL84WaMLkLnlYPmb8Ikm&sz=w400",
    deskripsi: "Target 1 BTC vs 0,1 BTC — kenapa 0,1 BTC sudah menempatkanmu jauh di atas mayoritas populasi dunia, dan mengapa Bitcoin lebih baik dijadikan aset warisan lintas generasi.",
  },
  {
    judul: "The Richest Man in Babylon — Ringkasan & Penerapannya di 2026",
    topik: "bookreview",
    jenis: "PDF",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-03-01",
    link: "https://drive.google.com/file/d/1vIJr1dYnXO6d_ubpitl6dwS3oB-xOVZb/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1vIJr1dYnXO6d_ubpitl6dwS3oB-xOVZb&sz=w400",
    deskripsi: "Ringkasan buku klasik karya George S. Clason beserta penerapan praktisnya di Indonesia 2026 — dari 7 prinsip membangun kekayaan hingga simulasi DCA Bitcoin.",
  },
  {
    judul: "Understanding Bitcoin: A 21-Day Tweet-a-Day Journey (Bahasa Indonesia)",
    topik: "bookreview",
    jenis: "PDF",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-06-18",
    link: "https://drive.google.com/file/d/1FKvjyDGumFN4nVoofTkMgS9OUCgX4MEk/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1FKvjyDGumFN4nVoofTkMgS9OUCgX4MEk&sz=w400",
    deskripsi: "Panduan Bitcoin 22 topik dalam Bahasa Indonesia — dari \"Apa itu Bitcoin?\" sampai membongkar mitos-mitos seperti soal energi, kriminalitas, dan larangan pemerintah. Cocok untuk pemula.",
  },
  {
    judul: "Thailand: Pasar Jimat Terbesar",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-19",
    link: "https://www.facebook.com/1216429964/posts/pfbid02wSPsaZtHuXX1p2VMjm99rj7SmRxY8cFn93QoAcmWgnXB6fYSmroQgNCbeqSBSyc6l/",
    thumbnail: "https://drive.google.com/thumbnail?id=1f1Yzh7h0Z7XrjAuaRNgxvp7_FpYLsjsy&sz=w400",
    deskripsi: "Cerita dari pasar jimat terbesar di Thailand — renungan soal kepercayaan, keberuntungan, dan apa yang sebenarnya orang cari lewat benda-benda semacam ini.",
  },
  {
    judul: "Episode 4 - Bitcoin White Paper: Sistem Keuangan Bitcoin Tanpa Perantara Bank",
    topik: "bitcoin",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-05",
    link: "https://open.spotify.com/episode/64XtEEHWugQbQqvHfWztvg",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8aeac1e37041a7de8e83709a19",
    deskripsi: "Membedah Bitcoin White Paper karya Satoshi Nakamoto — gimana sistem peer-to-peer ini menyelesaikan masalah double-spending tanpa butuh bank sebagai perantara.",
  },
  {
    judul: "Sunyi Licik",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DOdr8lxjw7C/",
    thumbnail: "https://drive.google.com/thumbnail?id=18K44QY0tyKI0KYLsVE-UF71glmAI1_nM&sz=w400",
    deskripsi: "Puisi singkat tentang kesunyian yang licik — kadang duduk di kursi, kadang merayap di pemandangan, membuat kita percaya ia sudah pergi.",
  },
  {
    judul: "Bitcoin Gagal Jadi Uang?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "annasahmads, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1L__fYs4fjDcgE1cv-mNoh3Zf8QeO1QXF/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1L__fYs4fjDcgE1cv-mNoh3Zf8QeO1QXF&sz=w400",
    deskripsi: "Menelusuri kenapa Bitcoin dianggap belum berhasil jadi uang dalam arti penuh, dan apa makna sebenarnya di balik fungsi uang itu sendiri.",
  },
  {
    judul: "Bitcoin with Awareness",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "bitcoinsports.id, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1AIIantk_qeFkhR2cMDQQEp3yipqg4LV4/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1AIIantk_qeFkhR2cMDQQEp3yipqg4LV4&sz=w400",
    deskripsi: "Memahami Bitcoin bukan sekadar dari sisi teknis, tapi dengan kesadaran penuh — apa makna kepemilikan, kebebasan, dan tanggung jawab di baliknya.",
  },
  {
    judul: "The Offline Node: Kenapa Bitcoin dan Agama Punya Satu Rahasia yang Sama",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1THfa45YpwsCxMlMgR_82MCSfIUSUsze0/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1THfa45YpwsCxMlMgR_82MCSfIUSUsze0&sz=w400",
    deskripsi: "Menggali kesamaan tak terduga antara Bitcoin dan agama — keduanya bertumpu pada satu rahasia yang sama: keyakinan tanpa perlu otoritas pusat.",
  },
  {
    judul: "Bitcoin Script: Bahasa Rahasia di Balik Uang Kita",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1HI6rw4YoSy3WP2FgJnYpEgnDjqavDTMG/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1HI6rw4YoSy3WP2FgJnYpEgnDjqavDTMG&sz=w400",
    deskripsi: "Bukan sekadar kode, ini adalah mantra yang menjaga triliunan dolar aset dunia — membongkar bahasa rahasia di balik Bitcoin Script.",
  },
  {
    judul: "Kartini & Bitcoin (sebuah obrolan santai tentang kasta, kebebasan dan feodalisme yang ganti skin)",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1LWH59Cn5CoM4mEn0-uwhPZD-Rm4dgSOq/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1LWH59Cn5CoM4mEn0-uwhPZD-Rm4dgSOq&sz=w400",
    deskripsi: "Obrolan santai tentang kasta, kebebasan, dan feodalisme yang ganti skin — menghubungkan semangat Kartini dengan perjuangan kebebasan finansial lewat Bitcoin.",
  },
  {
    judul: "Bitcoin Realistis: Panduan Waras di Dunia Gila (sebuah obrolan santai buat kita yang mau investasi tanpa kehilangan akal sehat)",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "annasahmads, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/10__hUqIFFrYkHV1Luy3FLfUuffUNjrjs/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=10__hUqIFFrYkHV1Luy3FLfUuffUNjrjs&sz=w400",
    deskripsi: "Obrolan santai buat kita yang mau investasi Bitcoin tanpa kehilangan akal sehat — panduan waras di tengah euforia dan kepanikan dunia kripto.",
  },
  {
    judul: "UTXO: Lu Pikir Bitcoin Kayak Saldo GoPay? Salah Besar, Bro!",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1GR7L30dRNfy9fPU1-bJfRPbvuae88nHD/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1GR7L30dRNfy9fPU1-bJfRPbvuae88nHD&sz=w400",
    deskripsi: "Di kepala kita, uang itu angka 'balance' yang cair. Tapi di Bitcoin nggak ada yang namanya saldo — kenalan sama konsep UTXO yang sebenarnya.",
  },
  {
    judul: "Soledad, Bitcoin, Winter Solstice & Old Soul",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "theuniverseismycampus, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.youtube.com/watch?v=euvf-LuPbyE",
    thumbnail: "https://img.youtube.com/vi/euvf-LuPbyE/hqdefault.jpg",
    deskripsi: "Refleksi tentang kesendirian, Bitcoin, titik balik musim dingin, dan jiwa yang tua — sebuah perenungan filosofis yang menghubungkan alam, waktu, dan Bitcoin.",
  },
  {
    judul: "Hamlet, Telur Dadar, Bitcoin | Filosofi Hidup yang Mengubah Cara Berpikir",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "theuniverseismycampus, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.youtube.com/watch?v=ln12U4i3kOs&t=135s",
    thumbnail: "https://img.youtube.com/vi/ln12U4i3kOs/hqdefault.jpg",
    deskripsi: "Dari dilema Hamlet sampai cara masak telur dadar — sebuah perjalanan filosofis yang mengubah cara berpikir tentang hidup dan Bitcoin.",
  },
  {
    judul: "Kalkulator DCA Bitcoin V3.0",
    topik: "bitcoin",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/p/kalkulator-dca-bitcoin-v30.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1DvjdJhgJsRYUzzWBYb4Y38u_kcIZ9_GW&sz=w400",
    deskripsi: "Alat bantu hitung simulasi Dollar Cost Averaging (DCA) Bitcoin — lihat potensi hasil investasi rutinmu dari waktu ke waktu.",
  },
  {
    judul: "AngkaCukup",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/p/angkacukup.html",
    thumbnail: "https://drive.google.com/thumbnail?id=19JC2FasckzlaOjAVoyBpRrMxgsLkRH9t&sz=w400",
    deskripsi: "Alat bantu menghitung 'angka cukup' kamu — berapa sebenarnya yang kamu butuhkan untuk merasa cukup secara finansial.",
  },
  {
    judul: "Kelakuan Trader: Menjelaskan Bitcoin",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DGw7rkPp6ed/",
    thumbnail: "https://drive.google.com/thumbnail?id=1bihgkzVOrgJj88omuqsipreBeikF7Qbb&sz=w400",
    deskripsi: "Potret jenaka tingkah laku trader saat mencoba menjelaskan Bitcoin — relate banget buat yang sering ngobrolin crypto sama orang awam.",
  },
  {
    judul: "Kelakuan Trader: Halving Kok Gini",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/C6Ag1-rpVfa/",
    thumbnail: "https://drive.google.com/thumbnail?id=135ttUr1KgGSQjhqEazqBb4aFfctjqUK7&sz=w400",
    deskripsi: "Reaksi trader menghadapi momen halving Bitcoin yang gak sesuai ekspektasi — santai tapi mengena.",
  },
  {
    judul: "Kaleng Kosong",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DOny5aED6kS/",
    thumbnail: "https://drive.google.com/thumbnail?id=1BkFMdtNxXnsUCIXFu8VBLd8RMyyXyhRu&sz=w400",
    deskripsi: "Setiap diinjak, ia berbunyi lebih keras — daripada orang penuh isi yang takut bersuara. Puisi singkat tentang kebisingan kosong versus kebijaksanaan yang diam.",
  },
  {
    judul: "Episode 5 - Sejarah Rupiah dari Nyawa ke Digital",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-05",
    link: "https://open.spotify.com/episode/7hOiJ9j9leb6c4F3EZcQP4",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Uang bukan sekadar alat berbelanja, tapi simbol kedaulatan dan saksi bisu jatuh bangunnya bangsa — menyelami perjalanan panjang mata uang Rupiah dengan bahasa yang santai dan penuh insight.",
  },
  {
    judul: "Cara Hidup \"In This Economy\" (Juni 2026) - Happy Ikigai",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/2026/06/cara-hidup-in-this-economy-juni-2026.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjf368lq-BedJepVu-WLXKgoHUysKbEr4HYa6eXnXMgjwwOjkVz42LgXs77r5i4nJ-CRZXXMrqjE25aIyTnUfAVqamnK2u0Tzf3gLMDKyT3zuRc759EdJd2xmYv8RZxtY3ChAsCRCnxwpHfjC7ByFN2YShy2v9P9A1L82zh-8sULrP9eddk0PLoWNKgESQ/s1168/2026a.jpg",
    deskripsi: "Tips bertahan dan tetap waras menjalani hidup di tengah tekanan ekonomi 'in this economy' versi Juni 2026 — ala Happy Ikigai.",
  },
  {
    judul: "Emas vs. Bitcoin: Peter Schiff X CZ - Happy Ikigai",
    topik: "bitcoin",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2025-12-01",
    link: "https://www.annasahmad.com/2025/12/emas-vs-bitcoin-peter-schiff-cz.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJQLPxJH9y-2lEn1YHeAs5LjHG_-eaHy5gll8Z5QaNwGjbTpGQ2Ar1OHCYtr4tNuk-SBh1K_eaTIOYqqf-ozAWnRe4QA2Maz_uwlmxKvzNAMa3JQds0kdd1ZwuxLD2sgQ2ciM6tCYUSN41L6Oqn1k4Or94LUM6hxWfPvahtgIgNLyvRWize_v7eTvwHqo/s1024/unnamed%20(54).jpg",
    deskripsi: "Adu pandangan klasik soal emas vs Bitcoin lewat perdebatan Peter Schiff dan CZ — cocok buat yang baru mulai belajar Bitcoin.",
  },
  {
    judul: "The Art of Secrets — Seni Melindungi Apa yang Paling Lu Cintai",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ZZjvUjYyEizikEqcjYNGhcVh03nv4uVx/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ZZjvUjYyEizikEqcjYNGhcVh03nv4uVx&sz=w400",
    deskripsi: "Ngobrolin kriptografi, blockchain, dan kenapa internet belum kiamat.",
  },
  {
    judul: "Seberapa Gila Keamanan 256-Bit?",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ijEzZqLeR3MR_WSOI9jAKWmGYaKHgXu3/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ijEzZqLeR3MR_WSOI9jAKWmGYaKHgXu3&sz=w400",
    deskripsi: "Kenapa sistem sekelas Bitcoin nyaris mustahil ditembus? Zoom-out dari sebuah kotak kecil sampai ke ujung tata surya.",
  },
  {
    judul: "Standar Siapa? — Editorial",
    topik: "bitcoinphilosophy",
    jenis: "Article",
    kontributor: "maxima.freiman, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://standarsiapa.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1owvtWe9YI2z8KOJb-GL0SVu_Fn4qX-x8&sz=w400",
    deskripsi: "Mempertanyakan standar yang selama ini dianggap baku — siapa yang sebenarnya menentukan ukuran 'normal', 'benar', dan 'bernilai' dalam hidup kita?",
  },
  {
    judul: "From Banking to Bitcoin",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/14s2_sK5Dgj6JM-t1CoXINWDZBgYTzI3h/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=14s2_sK5Dgj6JM-t1CoXINWDZBgYTzI3h&sz=w400",
    deskripsi: "Sebuah kisah transisi, keyakinan, dan membangun masa depan — dari mengelola uang, memahami uang, hingga membangun ulang sistem uang lewat Bitcoin.",
  },
  {
    judul: "DHIPA21 — Kepulauan & Pelita",
    topik: "bitcoin",
    jenis: "Blog",
    kontributor: "AH Prayo, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://dhipa21.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1rxIgyylv1zpo9mlmVbGDGC-59BZLThR2&sz=w400",
    deskripsi: "Zine independen untuk mereka yang percaya uang yang baik bisa mengubah peradaban — Bitcoin sebagai pelita baru dari kepulauan Nusantara, untuk dunia.",
  },
  {
    judul: "Mengubah Keyakinan",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2022-08-01",
    link: "https://www.annasahmad.com/2022/08/mengubah-keyakinan.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgh328chW1MKgaQLQT-GT6QU3u0VbVosGbjO8NqU9zO4LSRBEJ7a_DebHm_RFn-buDn-UN5IFPXcVL4UF_dBPALBcum06OVI0DnQck4c65RRSbLe4rbnt58EBVFiCj0OORQA6uTOw2tZEMIdO3qbmygGLKofi5eI8bhL2NkH0MXHzXm_Sf1UjTg1dt9/s1080/zonaperubahan.png",
    deskripsi: "Mengubah keyakinan bukan perkara mudah — sebuah renungan tentang bagaimana cara pandang kita terhadap dunia bisa membuka atau menutup pintu perubahan.",
  },
  {
    judul: "Episode 6 - Rahasia Penciptaan Uang dari Pulau Jekyll",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-06",
    link: "https://open.spotify.com/episode/4QZ814xjbdVaAysQjNWLS0",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Bongkar konspirasi Pulau Jekyll — pertemuan rahasia para bankir elit tahun 1910 yang melahirkan Federal Reserve dan mengubah cara dunia mencetak uang.",
  },
  {
    judul: "Sejarah Rupiah",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2025-11-28",
    link: "https://docs.google.com/presentation/d/1NeIfSvt4T4LqPdb_I02mzr6zC8oeAZyVYzMIylEWuVk/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ewPsMWUFM2qAd5kX6sJI8g7UtOwNzCmy&sz=w400",
    deskripsi: "Menelusuri perjalanan sejarah mata uang Rupiah dari masa ke masa — dibawakan dalam Bitcoin Indonesia Online Meetup.",
  },
  {
    judul: "They Didn't Protest, They Encrypted",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQk6devgZS6/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1BiSe7DN1dw8_jEg_RWXJ5xULY9bkNET-&sz=w400",
    deskripsi: "Mereka tidak berdemonstrasi, mereka mengenkripsi — sebuah ilustrasi yang merujuk pada A Cypherpunk's Manifesto: privasi adalah kebutuhan untuk masyarakat terbuka di era digital.",
  },
  {
    judul: "Sejarah Uang",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2025-10-26",
    link: "https://docs.google.com/presentation/d/1TKnOptiwxhV-DZyLW09GvukUdJdP1WANxKUv8-b8CgM/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1AHVFCC3gbcbionL8_k9uPXoFsNipmQ51&sz=w400",
    deskripsi: "Menelusuri perjalanan sejarah uang dari masa ke masa — dibawakan dalam komunitas Bitcoin Indonesia di Jakarta Barat.",
  },
  {
    judul: "Coffee for Value",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQGcYOjCmox/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1HGP4AMNQH42mt-jcWbUvtnxeHd6VonOj&sz=w400",
    deskripsi: "Tukar kopi dengan Bitcoin — sebuah ilustrasi sederhana tentang nilai, kepercayaan, dan pertukaran yang adil antara dua tangan dari dunia yang berbeda.",
  },
  {
    judul: "Before Money Was Printed, It Was Proof of Work",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DQGA7PZDDqw/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1ruWXG_CK7jzATPbqjiumTWrv1N4OkVyX&sz=w400",
    deskripsi: "Sebelum uang dicetak, ia adalah bukti kerja — ilustrasi yang menghubungkan konsep barter purba dengan Proof of Work yang menjadi fondasi Bitcoin hari ini.",
  },
  {
    judul: "Mau Cuan Doank, Tapi Gak Mau Volatil?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1w5e3f1_EO7TjOxW-QEtGySLO_Gpe3NoU/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1w5e3f1_EO7TjOxW-QEtGySLO_Gpe3NoU&sz=w400",
    deskripsi: "Analogi laut tenang vs laut dalam — kenapa cuan dan volatilitas tidak bisa dipisahkan, dan bagaimana mindset investor menghadapinya.",
  },
  {
    judul: "7 Level Pemahaman Bitcoin",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1rvdMYopF1Ly27AapzyQdtUhgl-Pz5uJJ/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1rvdMYopF1Ly27AapzyQdtUhgl-Pz5uJJ&sz=w400",
    deskripsi: "Learning Pyramid dari Awam hingga Sovereign — perjalanan memahami Bitcoin bukan soal harga, tapi naik level dalam memahami uang dan nilai.",
  },
  {
    judul: "Sejarah Fiat",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2025-11-09",
    link: "https://docs.google.com/presentation/d/1DF6JcBVvejp99i6aaq11S7nnZp9hUdOenyCRsEDj4WY/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ts_Q-6FSm2crLbQ6Zh5Z67IplxbOoD-g&sz=w400",
    deskripsi: "Menelusuri sejarah uang fiat dari masa ke masa — dibawakan dalam komunitas Bitcoin Indonesia di Jakarta Barat.",
  },
  {
    judul: "Bedah Bitcoin Whitepaper",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2026-02-08",
    link: "https://docs.google.com/presentation/d/1WFU_M6eCUOHmb57egOJeLa_1ptORq-yAAXtMjW7nx8o/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=16I524bEoigBiJpKrrdgOeZjgT4_eQ2CJ&sz=w400",
    deskripsi: "Membedah whitepaper Bitcoin karya Satoshi Nakamoto secara mendalam — dibawakan dalam komunitas Bitcoin Indonesia di Jakarta Barat.",
  },
  {
    judul: "Mencari Alasan",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DXLCAlND4mI/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=10N0apgct4tRYkJLvYF1hnW02FcRVuQ8V&sz=w400",
    deskripsi: "Kau sibuk menilai dunia rusak, tapi jarang memeriksa bagian mana dari dirimu yang ikut menyumbang retaknya. Puisi singkat tentang refleksi diri.",
  },
  {
    judul: "Uang",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DWWfln4jyc8/",
    thumbnail: "https://drive.google.com/thumbnail?id=1mg4tTtldhKkrOyYJTQGCFg9B4p2GzKn7&sz=w400",
    deskripsi: "Dalam banyak kasus, uang tidak membuat orang baru. Ia hanya menentukan suara mana yang dihitung dan mana yang diabaikan. Puisi singkat tentang uang dan kuasa.",
  },
  {
    judul: "Episode 8 - Bukan Salah Kopi Kamu Sulit Beli Rumah",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-17",
    link: "https://open.spotify.com/episode/2ZUBWWLx9MU8GrBXuX5QXH",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Membedah krisis kepemilikan rumah dari data dan struktur ekonomi objektif — bukan sekadar menuding kopi atau paylater, tapi menelusuri ketimpangan harga properti versus upah dan praktik land banking.",
  },
  {
    judul: "Macro Memo Citrini Research",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "datul",
    tanggal: "2026-06-19",
    link: "https://hidatulfikri.substack.com/p/kritik-terhadap-the-2028-global-intelligence",
    thumbnail: "https://drive.google.com/thumbnail?id=1DdjtfLuwzcOcw7_3TYgO9AOlrSGKyG0H&sz=w400",
    deskripsi: "Kritik terhadap skenario 'The 2028 Global Intelligence Crisis' dari Citrini Research — membahas bagaimana AI bisa meningkatkan produktivitas sekaligus menghancurkan permintaan konsumen.",
  },
  {
    judul: "Koreksi Bitcoin, Siklus Halving, & Makro — Nanovest x Bitcoin Indonesia Jakarta Meetup",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "datul",
    tanggal: "2026-06-19",
    link: "https://www.youtube.com/watch?v=adFNNVM0hWs&t=307s",
    thumbnail: "https://img.youtube.com/vi/adFNNVM0hWs/hqdefault.jpg",
    deskripsi: "Diskusi mendalam soal koreksi harga Bitcoin, siklus halving, dan kondisi makroekonomi — dibawakan dalam Jakarta Meetup kolaborasi Nanovest x Bitcoin Indonesia.",
  },
  {
    judul: "Bitcoin Standard Indonesia: Asset Price Calculator 2015-2025",
    topik: "bitcoin",
    jenis: "Tools",
    kontributor: "Dias",
    tanggal: "2026-06-19",
    link: "https://claude.ai/public/artifacts/f7381917-af03-48a6-99e9-e494fc922968",
    thumbnail: "https://drive.google.com/thumbnail?id=1iTeq8ieS1LHBCLZDWzuOl2wKNZPf6lx0&sz=w400",
    deskripsi: "Kalkulator interaktif untuk membandingkan harga berbagai aset di Indonesia dari tahun 2015 hingga 2025 — lihat bagaimana Bitcoin berperforma dibandingkan aset lainnya.",
  },
  {
    judul: "Sekarang Tantangannya Berbeda",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "theuniverseismycampus",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DZiaHUEAdCh1xuO2kQFeGq44j4lmOW8J9eHc2A0/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1UrAtCE-wWZs7B6QUQ969I0uUSBREBnR-&sz=w400",
    deskripsi: "Refleksi tentang tantangan hidup yang terus berubah bentuk — dulu dan sekarang menghadapi rintangan yang berbeda, tapi sama-sama butuh ketahanan.",
  },
  {
    judul: "Kedamaian Sering Kali...",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "theuniverseismycampus",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DZRxQtWgcGeFBd51DJCpxADdtQ-2H-4w3qDI7I0/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1CpUDKvs-3IJFEIQV_0kQmY2SQGZRciS6&sz=w400",
    deskripsi: "Kedamaian sering kali bukan tentang menemukan orang yang tepat, melainkan berhenti memaksa orang yang salah untuk ikut berjalan bersama.",
  },
  {
    judul: "Uangnya Ada Banyak, Tapi Gak Ada yang Mau",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DLkf12svZcu/",
    thumbnail: "https://drive.google.com/thumbnail?id=1vhPjfyB-4PhpjL_D2AhalmZOtyh8F46a&sz=w400",
    deskripsi: "Ilustrasi terinspirasi hiperinflasi Jerman 1920-an — gerobak penuh uang 200 miliar Mark, tapi tetap tidak cukup untuk sebungkus roti. Pelajaran soal nilai uang yang runtuh.",
  },
  {
    judul: "Kalo Kamu yang Lakuin Itu, Disebut Nipu",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DLh6emPvD4V/",
    thumbnail: "https://drive.google.com/thumbnail?id=1FPe1fPPIMCnKXfHDFEfbLLN_7ypa8Ger&sz=w400",
    deskripsi: "Sebuah sindiran tajam — kalo individu yang mencetak uang seenaknya, itu disebut menipu. Tapi kalo institusi yang melakukannya, kita sebut itu kebijakan moneter.",
  },
  {
    judul: "Janjikan Emas Tapi Kirimnya Kertas",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "bitcoinized",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DMhezMNNP9e/",
    thumbnail: "https://drive.google.com/thumbnail?id=1_RY5XYQ7KUO4odbbKxAFsLGAFJ3H0YUl&sz=w400",
    deskripsi: "Mengulas bagaimana sistem standar emas perlahan ditinggalkan — janji emas yang dulu mendasari uang kertas, kini cuma jadi kertas tanpa jaminan apa-apa.",
  },
  {
    judul: "Kelemahan Fiat, dan Mengapa Bitcoin",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2026-06-19",
    link: "https://docs.google.com/presentation/d/1TTXRk9JkkiQE7NGMgjQFpPwFhZlTIqoH3tqeUGrS_qo/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1YGX80UDWq7KR9b0XetknIM8JM4kKVMDs&sz=w400",
    deskripsi: "Membahas kelemahan-kelemahan mendasar dari sistem uang fiat, dan mengapa Bitcoin muncul sebagai alternatif yang layak dipertimbangkan.",
  },
  {
    judul: "Pengantar Ekonomi Austria — Sesi 3",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2026-06-19",
    link: "https://docs.google.com/presentation/d/1WC89B2zfJwqD5fi5yBJ6ZTaWcXgTIZlI9a1xcOEuUBc/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1B1tPouhiE630Cb6xsZAdYzOvA6VWTPaW&sz=w400",
    deskripsi: "Pengantar mazhab ekonomi Austria — kerangka pemikiran yang menekankan tindakan individu, nilai subjektif, dan kritik terhadap intervensi moneter.",
  },
  {
    judul: "Harga Bitcoin Saat Piala Dunia",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1T_rW-AwR6REv9URVjGWdYCgjaF5xiQDm/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1T_rW-AwR6REv9URVjGWdYCgjaF5xiQDm&sz=w400",
    deskripsi: "Pola historis BTC dari Piala Dunia 2010 hingga 2026 — bagaimana momentum global sebesar Piala Dunia berkorelasi dengan pergerakan harga Bitcoin.",
  },
  {
    judul: "Tugas Uang versi 2.0 (aka. dengan proteksi dan sudut Islami)",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2026-01-01",
    link: "https://www.annasahmad.com/2026/01/tugas-uang-versi-20-aka-dengan-proteksi.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh9PCHy9fzzGiVRTV7XPir0bmMla-qsf8QN9Nri5Y7t3hNC3R2mKi1kpgdqFlrlkeIKNYyifPR1kwz_HMoufYbGEEk8OK91UYUJd0sx3O1KnnIR5-9Xn4vcamg6ol1xlrl2zGbD6D1LI6oIuQlKb9baTYoT8HWBEVxr2bZyZ0AbpdEPUSQQrL1yex5Qr9g/s2816/Gemini_Generated_Image_e4u7q1e4u7q1e4u7.png",
    deskripsi: "Memperluas definisi tugas uang dengan tambahan proteksi dan sudut pandang Islami — sebuah refleksi tentang bagaimana uang seharusnya berfungsi secara utuh.",
  },
  {
    judul: "Building a Bitcoin Movement Across the World's Largest Archipelago",
    topik: "bitcoin",
    jenis: "Article",
    kontributor: "dhiemazalfa",
    tanggal: "2026-06-19",
    link: "https://proofofworkmagazine.com/magazine",
    thumbnail: "https://drive.google.com/thumbnail?id=1GiqHp_qaPyypNVrw5cVPq2yMcmwt4kv-&sz=w400",
    deskripsi: "Dari Proof of Work Magazine Vol. 04 (halaman 14) — menelusuri bagaimana gerakan Bitcoin tumbuh dan menyatukan masyarakat di seluruh kepulauan terbesar di dunia, Indonesia.",
  },
  {
    judul: "Market Structure & Smart Money Concept",
    topik: "technicalanalysis",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/18kLHyfGwOGmoJfmMrF980bpWAsUvtbRd/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=18kLHyfGwOGmoJfmMrF980bpWAsUvtbRd&sz=w400",
    deskripsi: "Memahami struktur pasar dan konsep Smart Money — bagaimana pelaku besar menggerakkan harga, dan cara membaca jejaknya lewat price action.",
  },
  {
    judul: "The JP77 Strategy Protocol",
    topik: "technicalanalysis",
    jenis: "PDF",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ScUh18Cmfu1siD5NA6mQ8o4-TYZNk_wf/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ScUh18Cmfu1siD5NA6mQ8o4-TYZNk_wf&sz=w400",
    deskripsi: "A Step-by-Step Blueprint for Disciplined Swing Trading — Traders Family Operational Guide.",
  },
  {
    judul: "Pengantar Ekonomi Austria — Sesi 1",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2026-06-19",
    link: "https://docs.google.com/presentation/d/1HuIOyq7kZ0_rkLXKsjiza6e3Rk39ZKMuV-RBCaktfHU/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1HV2wJ2zpBbh_MoGyW3OV5liN7SlStTba&sz=w400",
    deskripsi: "Pengantar mazhab ekonomi Austria sesi pertama — kerangka pemikiran yang menekankan tindakan individu, nilai subjektif, dan kritik terhadap intervensi moneter.",
  },
  {
    judul: "AI Mengalahkan Bitcoin",
    topik: "bitcoin",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://www.annasahmad.com/2026/06/ai-mengalahkan-bitcoin.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgoH0d0LRGHdtW3_ZCFQREKOjkVwSsk7nh6hgWnRl9oOtMuXXj3RQ9uNn4NoZlBlHRy8_Q2_OAd-iWaN-DcSKRSjz8wRUqtHQEVz7ht_ZFFXnUvmFg6XQZqTJRlb_j_Ft1M_tYhXLEg6vKxyXEVleJ7EUVFCS_eqGH2JA8LLo9zOtYe7M2hPtKHIo4S574/s1024/a745a7d3-12c5-429e-a0a0-2ca4d564c35c.jfif",
    deskripsi: "Mempertanyakan narasi AI sebagai investasi yang lebih menjanjikan dibanding Bitcoin — apakah benar AI bisa 'mengalahkan' Bitcoin, atau ini cuma narasi hype yang lain?",
  },
  {
    judul: "Bagaimana Cara Melepaskan?",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2023-08-01",
    link: "https://www.annasahmad.com/2023/08/bagaimana-cara-melepaskan.html",
    thumbnail: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjdUi75sZhuWb4brZqb-qJ7aI1DOIGnpyCOY2JmutuGQS3oInnkjc2CGunSwyGlPe8Kw3uJ8L4ORyRarDSy3ZyUqz4nGvm8w8VvkgvHR6pqXJHHEvRBX8CHxWzLlB2LJ36r_zBCpqFtum8Yf5vAh1N190fkbCtCCR3RApFattqzM-f5EyPRTD5SleeCV30/s1500/Letting+go.jpg",
    deskripsi: "Sebuah renungan tentang seni melepaskan — bagaimana kita bisa berdamai dengan kehilangan dan berhenti menggenggam apa yang sudah tidak lagi milik kita.",
  },
  {
    judul: "Kelakuan Trader: Buy the F***ing Dip",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "keloklompe",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DFsC00wpRzv/",
    thumbnail: "https://drive.google.com/thumbnail?id=1UgEjtg1VJuQoV5uGis9zDHI-rVTvoEip&sz=w400",
    deskripsi: "Reaksi khas trader saat harga Bitcoin koreksi tajam — antara panik dan semangat 'buy the dip' yang relate banget buat siapa pun yang pernah hodl.",
  },
  {
    judul: "Episode 1 - Blokade Selat Hormuz Kuras Milyaran Dolar Crypto",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-03",
    link: "https://open.spotify.com/episode/2zho3DIytPiszH7K6pdbXs",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a4247b29aeae6a2524488acc3",
    deskripsi: "Apakah aset digital benar-benar kebal dari krisis fisik di dunia nyata? Membedah bagaimana konflik geopolitik di Selat Hormuz bisa menghapus kekayaan kripto dalam sekejap.",
  },
  {
    judul: "Bukan Soal Kekuatan atau Jurus Ninja",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ycS70f4H5m90LTTMgm_lS1vWTmIflzkR/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ycS70f4H5m90LTTMgm_lS1vWTmIflzkR&sz=w400",
    deskripsi: "Apa kesamaan antara ninja paling berisik dan kreator uang paling misterius di dunia? Sebuah obrolan deep-talk buat yang lagi capek sama keadaan.",
  },
  {
    judul: "Kisah Ninja, Uang, dan Kita yang Lelah",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/14bZJE6OeNp4sy35Obm5I89_qXcLtIi5k/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=14bZJE6OeNp4sy35Obm5I89_qXcLtIi5k&sz=w400",
    deskripsi: "Ngobrol santai membahas rahasia terbesar dari dunia Naruto dan Satoshi Nakamoto — bukan soal jurus ninja atau tebak-tebakan grafik crypto, tapi sesuatu yang jauh lebih dalam.",
  },
  {
    judul: "Lu Pikir Ini Cuma Soal Jurus & Cuan?",
    topik: "bitcoinphilosophy",
    jenis: "PDF",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1qoCBgWX9OzwxvWBr_kEn2H9DNUGenivK/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1qoCBgWX9OzwxvWBr_kEn2H9DNUGenivK&sz=w400",
    deskripsi: "Filosofi tersembunyi di balik Naruto, Satoshi Nakamoto, dan seni menyatukan manusia di dunia yang hancur. Persiapkan diri — kita bakal turun ke rabbit hole terdalam.",
  },
  {
    judul: "Bitcoin Apocalypse 2140",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1kSGrABnCBsrZSfkkIYFZECXGEi3357De/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1kSGrABnCBsrZSfkkIYFZECXGEi3357De&sz=w400",
    deskripsi: "Simulasi Skenario & Resiliensi Jaringan — sebuah analisa cypherpunk tentang ketahanan Bitcoin ketika peradaban runtuh: listrik mati, internet padam, negara jatuh, namun ledger tetap hidup.",
  },
  {
    judul: "What We Think #1 — Kalau Dapat 10 Milyar",
    topik: "sapulidijournal",
    jenis: "PDF",
    kontributor: "sapulidi",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1F99xLYXrH38g4qIgIZcRAYmgrXajMcIL/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1F99xLYXrH38g4qIgIZcRAYmgrXajMcIL&sz=w400",
    deskripsi: "Seri jurnal pemikiran Rumah Baca Sapu Lidi — edisi pertama membahas pertanyaan klasik: kalau dapat 10 milyar, apa yang sebenarnya akan kamu lakukan?",
  },
  {
    judul: "Aturan Pajak Kripto 2026 untuk Trader Lokal",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1jYP4HKnH6VABfSjmul30r7HrANpwCJER/view?usp=drive_link",
    thumbnail: "https://drive.google.com/thumbnail?id=1jYP4HKnH6VABfSjmul30r7HrANpwCJER&sz=w400",
    deskripsi: "PPN kripto resmi dihapus sejak Agustus 2025, tarif PPh Final exchange lokal cuma 0,21% (vs 1% di exchange luar negeri), dan pengawasan kripto kini pindah ke OJK — infografis lengkap aturan pajak kripto 2026 untuk trader lokal.",
  },
  {
    judul: "Jangan Ukur Bitcoin dengan Rupiah",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1Yzk7cvmavY6xqxQntjzNguYxiYf26SKp/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1Yzk7cvmavY6xqxQntjzNguYxiYf26SKp&sz=w400",
    deskripsi: "Ukur rumah, mobil, pendidikan, dan masa depanmu dengan Bitcoin, bukan Rupiah — framework daya beli jangka panjang untuk berpikir lebih tenang, sabar, dan kaya perlahan.",
  },
  {
    judul: "Stay Humble, Keep Sats, Stay Human",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "AH Prayo",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DZ7j2NRyQu-/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA%3D%3D",
    thumbnail: "https://drive.google.com/thumbnail?id=13VG_0eqHlxuqOjNPeXmnR8YS-A5LYxAf&sz=w400",
    deskripsi: "Stay humble, keep sats, stay human — mantra sederhana dari Limau Oranje yang mengingatkan kita untuk tetap rendah hati, terus menabung Bitcoin, dan tetap manusiawi.",
  },
  {
    judul: "Apakah Uang Itu Persoalan Spiritual?",
    topik: "bitcoinphilosophy",
    jenis: "Article",
    kontributor: "bitkris.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DXJeLHUj75U/?igsh=cTM3ODJqOXZlbmlm",
    thumbnail: "https://drive.google.com/thumbnail?id=1vkSdX72l2nN0-GWJdBPZ02rVG9kA3fbR&sz=w400",
    deskripsi: "Cara kita mengelola uang mencerminkan apa yang kita percaya — sebuah pertanyaan reflektif tentang hubungan antara uang dan spiritualitas.",
  },
  {
    judul: "Semakin Banyak % Nett Wealth Anda dalam Bitcoin, Semakin Tinggi IQ Anda?",
    topik: "bitcoinmath",
    jenis: "Article",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DZQx6qUkpAO/?igsh=cjk1Z3NxazMweGdx",
    thumbnail: "https://drive.google.com/thumbnail?id=1fI-PUZRuiu8daHKcML_QFuvPJw-EIegA&sz=w400",
    deskripsi: "Sebuah klaim provokatif yang mengundang pertanyaan: benarkah persentase kekayaan bersih dalam Bitcoin berkorelasi dengan kecerdasan? Atau cuma bias konfirmasi semata?",
  },
  {
    judul: "HODL Bitcoin",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "bitcoinsports.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/reels/DZ84vyIp77x/",
    thumbnail: "https://drive.google.com/thumbnail?id=1vm8hK1NSOkFaZVcGZ_AFm6a56PJK8c7i&sz=w400",
    deskripsi: "Reel singkat tentang filosofi HODL — kenapa menahan dan tidak panik jual jadi salah satu strategi paling teruji dalam perjalanan investasi Bitcoin.",
  },
  {
    judul: "The Cage the Bird Couldn't See",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Bitcoin SatoshiCat, bitkris.id",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DYvpkMdgV_o/?img_index=1",
    thumbnail: "https://drive.google.com/thumbnail?id=1Ymvtgu5_QZACw_ZoZWl8eIxmb-ITuvkD&sz=w400",
    deskripsi: "Ketika mimpi mulai terasa terlalu jauh untuk diraih, dan burung baru sadar bahwa ia memerlukan sangkar yang ia kira ia cintai. Segalanya berawal dari mimpi.",
  },
  {
    judul: "Bitcoin Is Still Here, But Where Are the People?",
    topik: "bitcoin",
    jenis: "Art",
    kontributor: "Chresna Sanubari Putra, Bitcoin SatoshiCat",
    tanggal: "2026-06-19",
    link: "https://www.instagram.com/p/DY_f1xggc4W/",
    thumbnail: "https://drive.google.com/thumbnail?id=18qpkmPeS0vs-eqjbM_Yw6udziPA3KioE&sz=w400",
    deskripsi: "Bitcoin masih ada, tapi di mana orang-orangnya? Sebuah refleksi tentang adopsi Bitcoin yang masih tertinggal jauh dibandingkan teknologinya yang sudah matang.",
  },
  {
    judul: "Bitcoin: Panduan Praktis & Aplikatif",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Dias",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1DLrOzXEfAuCcYjiCN2yPwDAEEHYZu1FP/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1C8JhHXa91xheP393gukhcI70F-fvkuFx&sz=w400",
    deskripsi: "Dari dasar hingga strategi investasi jangka panjang — panduan praktis dan aplikatif untuk memahami Bitcoin secara menyeluruh.",
  },
  {
    judul: "Investment Policy Statement — Konstitusi Investasi Pribadi",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Dias",
    tanggal: "2026-06-19",
    link: "https://docs.google.com/document/d/1FXC9ZEMLM6vHYy8wpkrAzsYrh3jGl26g/edit?usp=drive_link&ouid=107664952402126331844&rtpof=true&sd=true",
    thumbnail: "https://drive.google.com/thumbnail?id=1yEu3gM8NvWDtdHJa7qbL_IRMC-IvZeif&sz=w400",
    deskripsi: "Sebuah dokumen konstitusi investasi pribadi — mendefinisikan horizon investasi, tujuan utama, dan review tahunan demi kebebasan finansial jangka panjang.",
  },
  {
    judul: "Retire Off Bitcoin Calculator",
    topik: "bitcoin",
    jenis: "Tools",
    kontributor: "Dias",
    tanggal: "2026-06-19",
    link: "https://docs.google.com/spreadsheets/d/1xmEtJEQIytU8_vP6ztt69WTHbXq2x6Q_IjGg5GIzv6Y/edit?gid=1566932447#gid=1566932447",
    thumbnail: "https://drive.google.com/thumbnail?id=1szNt7fayPVkJTmTlpeO6gqGa5c1eVVTJ&sz=w400",
    deskripsi: "Kalkulator simulasi nilai, gain, LTV, dan utang berdasarkan harga Bitcoin — bantu kamu memproyeksikan apakah memungkinkan untuk pensiun mengandalkan kekayaan Bitcoin.",
  },
  {
    judul: "Desa Bitcoin Hijau",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1ej7OSdQbteoZMyHt9W79JdWUKbV6C0CH/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ej7OSdQbteoZMyHt9W79JdWUKbV6C0CH&sz=w400",
    deskripsi: "Desa Mandiri, Energi Murah, Ekonomi Berdaulat — sebuah ekosistem tertutup yang menggabungkan energi terbarukan, mining Bitcoin, dan ekonomi lokal berbasis SATS untuk membangun kedaulatan desa dari akar.",
  },
  {
    judul: "Desa Bitcoin Hijau — Desa Mandiri, Energi Murah, Ekonomi Berdaulat",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/11YotNjwxmaKn2Ey-X_L8Z5kcj26sL9SG/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=11YotNjwxmaKn2Ey-X_L8Z5kcj26sL9SG&sz=w400",
    deskripsi: "Desa Mandiri, Energi Murah, Ekonomi Berdaulat — visualisasi ekosistem tertutup desa Bitcoin: mining hub, ATM Bitcoin, pasar dengan Sats, hingga close loop ecosystem yang membuat ekonomi lokal terus berputar.",
  },
  {
    judul: "Desa Bitcoin — Satu Ekosistem, Satu Mata Uang, Satu Tujuan",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1n5Q4-eSF-BlmHeDy9Xpg-nocWnLLCFMr/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1n5Q4-eSF-BlmHeDy9Xpg-nocWnLLCFMr&sz=w400",
    deskripsi: "\"We don't chase the future. We build it.\" — sebuah desa yang menggunakan Bitcoin (Sats) sebagai alat tukar, memanfaatkan energi murah untuk menambang, dan membangun ekosistem tertutup yang mandiri.",
  },
  {
    judul: "Mengapa SpongeBob Perlu Bitcoin?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat, Henry Sinaga",
    tanggal: "2026-06-19",
    link: "https://drive.google.com/file/d/1cwd5YIhCMSGA7R0dwnXFWv4J2Lgs-JED/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1pDazyru3TLu2TgDFTtg0eyzDNPzzUNlZ&sz=w400",
    deskripsi: "Sebuah analogi jenaka menggunakan dunia bawah laut Bikini Bottom untuk menjelaskan kenapa konsep Bitcoin relevan, bahkan untuk karakter seperti SpongeBob.",
  },
  {
    judul: "Untuk Apa Semua Ini?",
    topik: "filsafat",
    jenis: "Article",
    kontributor: "jokoart.id",
    tanggal: "2026-06-24",
    link: "https://jokowarihwiguna.blogspot.com/2026/06/untuk-apa-semua-ini.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1XlzN_3QFFi9CssLdt0UkKzR1GUDDZu2c&sz=w400",
    deskripsi: "Mencari kompas di tengah dunia yang terlalu bising untuk didengar — sebuah renungan tentang makna dan arah di tengah kebisingan hidup.",
  },
  {
    judul: "Planner Investasi Hidup",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-25",
    link: "https://www.annasahmad.com/p/uji-rencana-financial.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1nx3e4Aiih_UGWB2PYc6PIGfR_GgV7c1i&sz=w400",
    deskripsi: "Rencanain sekarang, capai masa depan. Hitung jalan menuju kebebasan finansial — kalkulator interaktif untuk target investasi, perencanaan pensiun, dan kebebasan finansial.",
  },



  {
    judul: "Yang Bikin Bankrut bukan Harga Anjlok. Tapi Time Pain!",
    topik: "ekonomi",
    jenis: "Article",
    kontributor: "annasahmads",
    tanggal: "2026-06-25",
    link: "https://lynk.id/annasahmad/kk2drv7ned29",
    thumbnail: "https://drive.google.com/thumbnail?id=1ijti0JhNKUsJ3wOrKEC__3biQPtYyE0x&sz=w400",
    deskripsi: "Trust the Process, WAGMI, Me Meyakinkan Diri: HODL Berusaha Terus — psikologi seorang Bitcoin HODLer yang tetap tenang di tengah deep loss dan volatilitas pasar.",
  },



  {
    judul: "Bitcoin: Dari Pemula Hingga Ahli",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "igp kanda",
    tanggal: "2025-09-02",
    link: "https://www.youtube.com/watch?v=12QoBjSdyWQ",
    thumbnail: "https://img.youtube.com/vi/12QoBjSdyWQ/hqdefault.jpg",
    deskripsi: "Menggali dunia Bitcoin melalui komunikasi dua arah yang interaktif bersama para ahli dan praktisi Bitcoin dari Jakarta — menjawab pertanyaan seputar apa itu Bitcoin, untuk apa membelinya, cara berinvestasi dengan aman, serta keuntungan dan kerugiannya.",
  },



  {
    judul: "Bitcoin Indonesia Conference 2025 — Kenapa Keamanan Siber Penting untuk Menjaga Bitcoin Kita?",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "igp kanda",
    tanggal: "2025-09-09",
    link: "https://www.youtube.com/watch?v=C-_6MZtLO8A",
    thumbnail: "https://img.youtube.com/vi/C-_6MZtLO8A/hqdefault.jpg",
    deskripsi: "Diskusi pentingnya kesadaran keamanan siber untuk menjaga Bitcoin kita, dibahas dalam Bitcoin Indonesia Conference 2025.",
  },



  {
    judul: "Membangun Keyakinan atas Bitcoin (Meet Up Bitcoin Indonesia Bintaro)",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "igp kanda",
    tanggal: "2025-08-18",
    link: "https://www.youtube.com/watch?v=RBhtI7n3RBU&t=2556s",
    thumbnail: "https://img.youtube.com/vi/RBhtI7n3RBU/hqdefault.jpg",
    deskripsi: "Meet up rutin setiap bulan Bitcoin Indonesia di Bintaro — membangun keyakinan atas Bitcoin bersama komunitas. Untuk jadwal cek ke sosial media Bitcoin Indonesia.",
  },




  {
    judul: "Mengapa Bitcoin Bukan Hanya Soal Uang, Tapi Soal Kemerdekaan Jiwa",
    topik: "bitcoin",
    jenis: "Article",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-06-26",
    link: "https://www.facebook.com/awangbikal/posts/pfbid0F11Dit8fuUR73U16BoDGykc5ePsCmbJbGRc5Frcg9euMX7uxuwoxrdPxQ7CTb5vil",
    thumbnail: "https://drive.google.com/thumbnail?id=1Gd-IRF-3LLSO8vXWhvqU8Yf08Vj_WD-_&sz=w400",
    deskripsi: "Setelah hampir setahun mempelajari Bitcoin, penulis sampai pada kesimpulan bahwa Bitcoin bukan soal grafik naik-turun — melainkan tentang kedaulatan individu, pembebasan dari ilusi sistem fiat, dan semangat Cypherpunk untuk merdeka secara finansial.",
  },



  {
    judul: "Manifesto Seorang Stoic Bitcoiner",
    topik: "filsafat",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-06-26",
    link: "https://drive.google.com/file/d/1SE7r7YpEq2pOztJFnA7ksJY8ED-iX0Ln/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1SE7r7YpEq2pOztJFnA7ksJY8ED-iX0Ln&sz=w400",
    deskripsi: "Tenang. Berpikir. Membangun. Bukan Mengejar. Bukan Mengeluh. — 8 prinsip seorang Stoic Bitcoiner: mengendalikan reaksi, mengejar pemahaman, membangun bukan sekadar berkomentar, dan menjadikan karakter sebagai pondasi.",
  },



  {
    judul: "Menembus Kabut Konspirasi: Memahami Kebenaran di Balik Bitcoin dan Kriptografi",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "jokoart.id",
    tanggal: "2026-06-27",
    link: "https://drive.google.com/file/d/1fb0kfxveUE877_j9FZrNWrNJeSqGTKM1/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1hArzWUFiDF4PPYXKLx5tHZMRQEogHKtv&sz=w400",
    deskripsi: "Fenomena video viral tokoh berwibawa yang mengklaim Bitcoin adalah alat konspirasi intelijen — PDF ini membedah sesat pikir argumentum ad verecundiam dan meluruskan kebenaran di balik Bitcoin dan kriptografi dengan bukti teknis.",
  },



  {
    judul: "Bitcoin 101 Indonesia #1",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "igp kanda",
    tanggal: "2026-06-27",
    link: "https://www.youtube.com/watch?v=Fx_A9Bj-INg&t=1108s",
    thumbnail: "https://img.youtube.com/vi/Fx_A9Bj-INg/hqdefault.jpg",
    deskripsi: "Seri Bitcoin 101 Indonesia — episode pertama untuk pemula yang ingin memahami Bitcoin dari dasar.",
  },



  {
    judul: "Dua Dunia Bitcoin yang Sangat Berbeda",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-06-27",
    link: "https://drive.google.com/file/d/17GVu4gXGHGd09uQQG-F3gUGsqIKt69H0/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=17GVu4gXGHGd09uQQG-F3gUGsqIKt69H0&sz=w400",
    deskripsi: "Masalah Berbeda, Solusi Sama — di negara maju Bitcoin adalah investasi, di Global South Bitcoin adalah kebutuhan: bayar, kirim uang, simpan nilai, dan akses keuangan tanpa bank.",
  },



  {
    judul: "Apa itu Bitcoin? — Bitcoin itu Cuma Catatan",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-06-27",
    link: "https://www.youtube.com/shorts/cC9Qjyf6ey4",
    thumbnail: "https://img.youtube.com/vi/cC9Qjyf6ey4/hqdefault.jpg",
    deskripsi: "Penjelasan singkat dan sederhana: Bitcoin itu cuma catatan. Short video yang memperkenalkan konsep dasar Bitcoin dengan cara paling mudah dipahami.",
  },



  {
    judul: "Siapa Mengendalikan Uang?",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-06-27",
    link: "https://www.youtube.com/shorts/AUewS7oGupk",
    thumbnail: "https://img.youtube.com/vi/AUewS7oGupk/hqdefault.jpg",
    deskripsi: "Siapa sebenarnya yang mengendalikan uang kita dan bagaimana sistem itu bekerja? Short video yang membuka mata tentang kendali di balik sistem keuangan.",
  },



  {
    judul: "Rebalancing Portfolio",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-28",
    link: "https://www.jurnaltrading.online/p/rebalancing-portfolio.html#",
    thumbnail: "https://drive.google.com/thumbnail?id=1Iiqtq_K6YMLjuitORDxFtQnHNpR7caxe&sz=w400",
    deskripsi: "Dashboard portofolio interaktif — pantau Gross Net Worth, True Wealth, dan Rasio Aset Produktif. Kelola alokasi aset (Cash, Saham, Emas, Bitcoin, Property, Bisnis) dan lakukan rebalancing menuju target alokasi ideal.",
  },



  {
    judul: "Apakah Perlu Punya Bitcoin Sekarang?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-29",
    link: "https://drive.google.com/file/d/1iPOObMjVOf--Udyl0zXy3cEkkNqELBkj/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1iPOObMjVOf--Udyl0zXy3cEkkNqELBkj&sz=w400",
    deskripsi: "Sebuah refleksi singkat gaya Cypherpunk — dan bagaimana jika kamu tidak peduli, alias belum sadar? Manifesto singkat yang mengajak berpikir ulang tentang urgensi memiliki Bitcoin sekarang.",
  },



  {
    judul: "Bitcoin vs Inflasi",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-29",
    link: "https://drive.google.com/file/d/1IGaWpH810XudDs3xJwCnz3I8zq2zW9GU/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1IGaWpH810XudDs3xJwCnz3I8zq2zW9GU&sz=w400",
    deskripsi: "Seberapa kuat & lama Bitcoin Treasury menahan laju inflasi? Presentasi strategis tentang Orange Manifesto, Digital Gold, dan Time Discipline dalam konteks Bitcoin sebagai pelindung nilai.",
  },



  {
    judul: "Portfolio Investment Strategy — 3-Year Projection Analysis",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "Aryo Utomo",
    tanggal: "2026-06-29",
    link: "https://docs.google.com/spreadsheets/d/1MDA8Y6ZLvTpIgDza0QnIFL3P2s3NYtpE/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1_F4_AYYBJlMXOEqj959CPPp7aJ1gGa7_&sz=w400",
    deskripsi: "Spreadsheet analisis proyeksi portofolio 3 tahun — bandingkan skenario Conservative, Moderate, dan Aggressive di kondisi Bull, Bear, dan Sideways. Lengkap dengan Key Metrics, Return Comparison, dan Recommended Allocation.",
  },



  {
    judul: "Financial Freedom Calculator",
    topik: "ekonomi",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-06-29",
    link: "https://www.annasahmad.com/p/financial-freedom-calculator.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1njviLUpkw6HmyPTxTEVRqIgNEMGyi0OP&sz=w400",
    deskripsi: "Kalkulator Kebebasan Finansial Bitcoin — pahami risikonya, hitung kebutuhan Anda. Sebelum memulai, pastikan Anda memahami konsep-konsep dasar dan risiko strategi ini.",
  },



  {
    judul: "Bitcoin Volatility and the Rise",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-02",
    link: "https://www.youtube.com/watch?v=U_FW8c3FDbE",
    thumbnail: "https://img.youtube.com/vi/U_FW8c3FDbE/hqdefault.jpg",
    deskripsi: "Bitcoin sebagai bentuk revolusioner dari digital capital — membandingkan volatilitas pasarnya saat ini dengan masa-masa awal pertumbuhan raksasa teknologi.",
  },



  {
    judul: "Bitcoin 2140: Survival After the Final Coin Mining",
    topik: "bitcoin",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-02",
    link: "https://www.youtube.com/watch?v=33qBcmYOuJ4",
    thumbnail: "https://img.youtube.com/vi/33qBcmYOuJ4/hqdefault.jpg",
    deskripsi: "Bitcoin mendekati batas maksimum 21 juta koin yang diproyeksikan tercapai tahun 2140 — bagaimana jaringan bertahan saat block reward habis dan beralih sepenuhnya ke sistem yang didanai oleh transaction fees?",
  },



  {
    judul: "That's How Blockchain Works",
    topik: "bitcoin-kids",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-02",
    link: "https://www.youtube.com/shorts/XAut7rebICU",
    thumbnail: "https://img.youtube.com/vi/XAut7rebICU/hqdefault.jpg",
    deskripsi: "Animasi singkat dan sederhana yang menjelaskan cara kerja blockchain — cocok untuk anak-anak dan siapa saja yang baru mulai belajar.",
  },
  {
    judul: "History of Money in 20 Seconds",
    topik: "bitcoin-kids",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-02",
    link: "https://www.youtube.com/shorts/zSRJx6XsuQo",
    thumbnail: "https://img.youtube.com/vi/zSRJx6XsuQo/hqdefault.jpg",
    deskripsi: "Sejarah uang dalam 20 detik — ringkas, visual, dan mudah dipahami semua usia.",
  },
  {
    judul: "Why Is Inflation Invisible?",
    topik: "bitcoin-kids",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-03",
    link: "https://www.youtube.com/shorts/-BKq9v1ENqM",
    thumbnail: "https://img.youtube.com/vi/-BKq9v1ENqM/hqdefault.jpg",
    deskripsi: "Kenapa inflasi sulit kita sadari? Animasi singkat yang menjelaskan konsep inflasi dengan cara mudah dan menyenangkan untuk anak-anak.",
  },
  {
    judul: "Apa Itu Elastic Money?",
    topik: "ekonomi",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-07-03",
    link: "https://drive.google.com/file/d/16cZ2lesRGHqqb63ar5htkcf5MXna2-OD/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=16cZ2lesRGHqqb63ar5htkcf5MXna2-OD&sz=w400",
    deskripsi: "Uang yang jumlahnya bisa bertambah atau berkurang sesuai kebutuhan ekonomi — konsep dari ekonomi Austria, dijelaskan lewat analogi jalan tol dan visual yang mudah dipahami.",
  },
  {
    judul: "Episode 9 - Putin Putus Rantai Riba Rothschild",
    topik: "ekonomi",
    jenis: "Podcast",
    kontributor: "Kurniawan Doank",
    tanggal: "2026-07-02",
    link: "https://open.spotify.com/episode/15PrTPZpL3kyj9XhJqSB6X",
    thumbnail: "https://i.scdn.co/image/ab6765630000ba8a7238de2e493d920863e5cef2",
    deskripsi: "Membahas langkah Putin memutus ketergantungan ekonomi Rusia dari sistem perbankan global, lewat nasionalisasi aset, pelunasan utang luar negeri, penguatan cadangan emas, dan dedolarisasi bersama BRICS.",
  },



  {
    judul: "Panduan Lengkap Electrum Bitcoin Wallet",
    topik: "bitcointechnicals",
    jenis: "Infographic",
    kontributor: "jokoart.id",
    tanggal: "2026-07-05",
    link: "https://drive.google.com/file/d/1vwIumvB3f9YnkHC2UeqbYUwU65jFrt3u/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1vwIumvB3f9YnkHC2UeqbYUwU65jFrt3u&sz=w400",
    deskripsi: "Simpan Bitcoin Sendiri — Aman, Praktis, Jangka Panjang. Panduan lengkap 11 langkah: download Electrum, siapkan flashdisk, masuk wallet, komponen penting, aturan wajib, skenario darurat, hingga cara menyimpan seed dengan aman. Siapa pegang seed, dia pegang Bitcoin.",
  },



  {
    judul: "The World's Biggest Illusion",
    topik: "bitcoin-kids",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-05",
    link: "https://www.youtube.com/shorts/tRAyMdzajTE",
    thumbnail: "https://img.youtube.com/vi/tRAyMdzajTE/hqdefault.jpg",
    deskripsi: "Ilustrasi singkat tentang fractional reserve banking — ilusi terbesar dalam sistem keuangan dunia, dijelaskan dengan visual yang mudah dipahami.",
  },



  {
    judul: "The Biggest Secret About Money",
    topik: "bitcoin-kids",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-05",
    link: "https://www.youtube.com/shorts/7l8pZH4jkJM",
    thumbnail: "https://img.youtube.com/vi/7l8pZH4jkJM/hqdefault.jpg",
    deskripsi: "Rahasia terbesar tentang uang — kebanyakan orang mengira uang adalah kekayaan, padahal kekayaan sejati adalah barang dan jasa nyata. Short video animasi yang menjelaskan konsep ini dengan cara yang mudah dipahami semua usia.",
  },



  {
    judul: "Bitcoin untuk Oma & Opa",
    topik: "bitcoin-grandparents",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-05",
    link: "https://drive.google.com/file/d/1-R0uFXQxz7KuHIuM5pk9uY-Iwlr9BPaM/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1-R0uFXQxz7KuHIuM5pk9uY-Iwlr9BPaM&sz=w400",
    deskripsi: "Menjaga Nilai, Melengkapi Masa Depan — penjelasan Bitcoin untuk orang tua dengan analogi mudah: tanah digital, emas modern, cara kerjanya, kenapa harganya naik turun, dan pentingnya diversifikasi. Bukan untuk cepat kaya, tapi untuk menjaga nilai kekayaan jangka panjang.",
  },



  {
    judul: "Secangkir Teh & Bitcoin",
    topik: "bitcoin-grandparents",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-07-05",
    link: "https://drive.google.com/file/d/1emhOOdLeJBDOECBqCqyZ52Zxzts-mqX9/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1emhOOdLeJBDOECBqCqyZ52Zxzts-mqX9&sz=w400",
    deskripsi: "Sebuah obrolan santai tentang warisan, zaman yang berubah, dan kebijaksanaan yang tetap sama — pendekatan hangat dan relatable untuk menjelaskan Bitcoin kepada generasi yang lebih tua.",
  },



  {
    judul: "Menjaga Nilai di Era Uang yang Dicetak Tanpa Batas",
    topik: "bitcoin-grandparents",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-06",
    link: "https://drive.google.com/file/d/1GAg3F8EhWif31FSbTlgZzObBnbdM8v3j/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1GAg3F8EhWif31FSbTlgZzObBnbdM8v3j&sz=w400",
    deskripsi: "Bitcoin untuk Old Money — perpaduan konsep Time Freedom of Money dan Orange Manifesto, dijelaskan dengan bahasa yang tenang, elegan, dan mudah dipahami. Sebuah edukasi hangat dari cucu untuk Oma & Opa.",
  },



  {
    judul: "Pengantar Ekonomi Austria — Sesi 2: Teori Hazlitt",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "mithos_btc",
    tanggal: "2026-05-03",
    link: "https://docs.google.com/presentation/d/1HuIOyq7kZ0_rkLXKsjiza6e3Rk39ZKMuV-RBCaktfHU/edit?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=10yF4GWfG8EnGWjnApzatS4LzLulHwuAj&sz=w400",
    deskripsi: "Sesi kedua dari seri Pengantar Ekonomi Austria — membahas Teori Hazlitt dalam konteks ekonomi dan Bitcoin. Dipresentasikan oleh @mithos_btc di Jakarta Barat, 3 Mei 2026.",
  },



  {
    judul: "Ciri Literasi Rendah & Jebakan FOMO",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-07",
    link: "https://drive.google.com/file/d/1wXFnBZatmed0f2oVsr9qApGM6N9G9ca0/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1wXFnBZatmed0f2oVsr9qApGM6N9G9ca0&sz=w400",
    deskripsi: "Mengapa banyak orang salah paham tentang Bitcoin — dan bagaimana manifesto Bitcoin menjawabnya. Sebuah panduan berpikir tentang ciri literasi rendah dan jebakan FOMO dalam dunia kripto.",
  },



  {
    judul: "Zero-Sum vs Positive-Sum",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-07",
    link: "https://drive.google.com/file/d/1yPdZk0oA6ArN9DXhkNym0O41qf5K_3aw/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1yPdZk0oA6ArN9DXhkNym0O41qf5K_3aw&sz=w400",
    deskripsi: "Memahami Bitcoin di balik FOMO, Panic Selling & Short Trading — dipadukan dengan semangat Cypherpunk Manifesto. Cypherpunks write code.",
  },



  {
    judul: "Mengapa Pemahaman Bitcoin Masih Rendah?",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-07",
    link: "https://drive.google.com/file/d/14JJ8RvEIxTL1QTUzskGJtuKtHwgq61Dw/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=14JJ8RvEIxTL1QTUzskGJtuKtHwgq61Dw&sz=w400",
    deskripsi: "9 Pola Pikir yang Menahan Orang untuk Paham — bukan Bitcoin-nya yang salah, tapi cara pandangnya yang keliru. Dari zero sum game, mindset untung saja, spekulasi, hingga anggapan Bitcoin = scam.",
  },



  {
    judul: "Kebenaran Tentang Bitcoin",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-07",
    link: "https://drive.google.com/file/d/1pRJW05_uFpfVGvzVlIhvTekSA2lk1rnu/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1pRJW05_uFpfVGvzVlIhvTekSA2lk1rnu&sz=w400",
    deskripsi: "Volatilitas ≠ Penipuan, 'Cepat Kaya' itu Ilusi, Influencers ≠ Pengetahuan, Tidak Ada Kantor/CEO bukan kelemahan tapi desentralisasi, dan Pencipta Anonim: Kode > Kepribadian. Lima kebenaran tentang Bitcoin yang sering disalahpahami.",
  },



  {
    judul: "Zero-Sum Game vs Positive-Sum Game",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-07",
    link: "https://drive.google.com/file/d/1xOchFDDuTKNh-BblHoRe-zPKx1vVj-qJ/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1xOchFDDuTKNh-BblHoRe-zPKx1vVj-qJ&sz=w400",
    deskripsi: "Memahami Bitcoin di balik FOMO, Panic Selling, dan Short Trading — perbandingan Zero-Sum (menang = rugi orang lain) vs Positive-Sum (semua peserta bisa menang), tiga jebakan psikologis, dan Bitcoin sebagai realisasi Manifesto Cypherpunk.",
  },



  {
    judul: "The Rise of \"Financial Nihilism\": Why Gen Z Treats the Stock and Crypto Like a Casino",
    topik: "ekonomi",
    jenis: "Video",
    kontributor: "annasahmads",
    tanggal: "2026-07-08",
    link: "https://www.youtube.com/watch?v=j637zK7_xjQ",
    thumbnail: "https://img.youtube.com/vi/j637zK7_xjQ/hqdefault.jpg",
    deskripsi: "Rencana tradisional menabung, beli rumah, dan membangun ekuitas sudah resmi rusak. Ketika Gen Z terkunci dari kepemilikan properti dan uang tak lagi menyimpan nilai, muncullah Financial Nihilism — tren brilian adaptasi sistem rusak, atau tanda darurat kolektif?",
  },



  {
    judul: "Trading For Living — Kalkulator Modal Trading",
    topik: "technicalanalysis",
    jenis: "Tools",
    kontributor: "annasahmads",
    tanggal: "2026-07-08",
    link: "https://www.jurnaltrading.online/p/trading-for-living.html",
    thumbnail: "https://drive.google.com/thumbnail?id=1ZI7LdxV2MaG7EEg6aL8wt1AWd1J0WGKe&sz=w400",
    deskripsi: "Hitung kebutuhan modal ideal berdasarkan biaya hidup, win rate, dan manajemen risiko — kalkulator interaktif untuk trader yang ingin hidup dari trading secara konsisten.",
  },



  {
    judul: "The Remora's Guide to Surviving the Market",
    topik: "technicalanalysis",
    jenis: "PDF",
    kontributor: "annasahmads",
    tanggal: "2026-07-09",
    link: "https://drive.google.com/file/d/1NTT7V9a85qONKgEUFF5tYe_9blCOLOZB/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1NTT7V9a85qONKgEUFF5tYe_9blCOLOZB&sz=w400",
    deskripsi: "Ekosistem pasar yang brutal, jenjang karir trader, dan Golden Rules untuk retail trader — kamu adalah ikan kecil yang mencoba mengambil remah-remah tanpa ikut terhancurkan oleh whale yang mendikte arus.",
  },



  {
    judul: "Profesi Potensial untuk Bitcoiner",
    topik: "ekonomi",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-07-09",
    link: "https://drive.google.com/file/d/1Sow4L_7uyO3XnzIT9dtOMDu9yiLqr9T6/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1Sow4L_7uyO3XnzIT9dtOMDu9yiLqr9T6&sz=w400",
    deskripsi: "Ubah pengetahuanmu jadi penghasilan! 12 profesi potensial untuk Bitcoiner: Content Creator, Trainer/Mentor, Konsultan Bitcoin, Penulis Artikel, Research Analyst, Community Manager, Translator, Technical Support, Node Installer, Lightning Consultant, Bitcoin Developer, hingga Designer Bitcoin.",
  },
  {
    judul: "Bitcoin Archetype Assessment",
    topik: "bitcoin",
    jenis: "Tools",
    kontributor: "Aryo Utomo, Bitcoin SatoshiCat",
    tanggal: "2026-07-11",
    link: "https://bitcoinarchetype.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1nc3Q8R0LNZlNYl77HLyvO8yDANL4GMK3&sz=w400",
    deskripsi: "40 pertanyaan singkat tentang cara berpikirmu — mindset, keputusan, kolaborasi, dan pandanganmu soal Bitcoin. Di akhir, kamu akan menemukan tiga arketipe yang paling menggambarkan dirimu.",
  },
  {
    judul: "The Mind-Heist: Three Musketeers of Persuasion",
    topik: "filsafat",
    jenis: "PDF",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/1cYd1Wd6udgwZ8eIR0MRL8XJSRnLRAB1Y/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1cYd1Wd6udgwZ8eIR0MRL8XJSRnLRAB1Y&sz=w400",
    deskripsi: "Lu pernah ngerasa argumen lu udah logis banget, pake data valid, tapi kok orang tetep nggak peduli? Persuasi itu bukan cuma modal bacot atau lempar data mentah. Ini soal seni meretas pikiran orang lain — butuh taktik, probabilitas matematika, dan sedikit sentuhan filsafat.",
  },
  {
    judul: "Trading, Ego, dan Cara Bertahan di Market",
    topik: "technicalanalysis",
    jenis: "PDF",
    kontributor: "annasahmads",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/18Okr1144IseRDl1L9UiBHEPzPXP4s1pd/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ZgUyO9pLhssY0iac3JOZy2zhiVYrleUT&sz=w400",
    deskripsi: "Rangkuman santai tentang psikologi trading — soal kenapa kita gampang hancur di market, dan apa yang sebenarnya bikin orang bisa terus bertahan.",
  },
  {
    judul: "16 Aliran Bitcoiner",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/1CMIq_gUv05UbZM5aoi8qdiNNLUYdKOHI/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1CMIq_gUv05UbZM5aoi8qdiNNLUYdKOHI&sz=w400",
    deskripsi: "Peta lengkap peran di dalam kota Bitcoin — dari educator hingga maximalist. Orange Pilled Edition.",
  },
  {
    judul: "Kenapa Uang Dicetak Terus?",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/1XA5YQ36TDsi6r8kh8d_4SsBDDtPNmgBr/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1XA5YQ36TDsi6r8kh8d_4SsBDDtPNmgBr&sz=w400",
    deskripsi: "Krisis keuangan, inflasi tinggi, jebakan hutang — dan kenapa Bitcoin muncul sebagai jalan keluar. Sebuah analisis sederhana.",
  },
  {
    judul: "Strategi Bertahan di Negara Krisis Hutang",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/1OBGsyFIvbsr3TZukb-8SuMY-Zbl1WBlB/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1OBGsyFIvbsr3TZukb-8SuMY-Zbl1WBlB&sz=w400",
    deskripsi: "Inflasi tinggi. Hutang menggunung. Sistem fiat retak. Dan bagaimana Bitcoin menjadi pintu keluar untuk kebebasan waktu & finansial. Studi kasus: Yunani, Argentina, Indonesia.",
  },
  {
    judul: "Jenis-Jenis Bitcoiner: Dari Edukasi Hingga Kedaulatan Finansial",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-11",
    link: "https://drive.google.com/file/d/1t5aumIsDh2OIcI87ad4_zlVBP4aq_6Of/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1t5aumIsDh2OIcI87ad4_zlVBP4aq_6Of&sz=w400",
    deskripsi: "Peta 16 jenis Bitcoiner dalam satu jaringan bebas & terdesentralisasi — dari Educator, Adopter, Riset, Mining, Node Runner, Realistik & Stoik, Bisnis, Investment, Macro & On-Chain, Sosial Impact, Circular Economy, Leverage, Developer, Community & Volunteer, Trader, hingga Maximalis. Berbeda jalan, satu tujuan: kebebasan finansial & kedaulatan individu.",
  },
  {
    judul: "Mining Bitcoin Itu Gimana Sih?",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-07-11",
    link: "https://www.youtube.com/post/UgkxX96L3CUajumRHE08w2SM9HH66wajWL8o",
    thumbnail: "https://drive.google.com/thumbnail?id=1plsCYgCOrA2B4MrR3s0gZEE_jgvKioPw&sz=w400",
    deskripsi: "Penjelasan sederhana tentang cara kerja mining Bitcoin — mulai dari transaksi masuk, dikumpulkan jadi blok, para miner berlomba memecahkan teka-teki matematika, hingga miner dapat hadiah dan blok terhubung ke blockchain.",
  },
  {
    judul: "Jika Marcus Aurelius Menilaimu",
    topik: "filsafat",
    jenis: "Tools",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-07-11",
    link: "https://sapulidirbsl.github.io/stoikquiz/",
    thumbnail: "https://drive.google.com/thumbnail?id=1Tywse6hUG3wyi0wbxnZB56aW0uNMPc-7&sz=w400",
    deskripsi: "Akankah para filsuf menganggapmu cukup bijaksana? Selama lebih dari dua ribu tahun, empat filsuf Stoik — Marcus Aurelius, Epictetus, Seneca, dan Cato the Younger — meninggalkan cara berpikir yang terus menginspirasi dunia. Mereka akan memberimu beberapa situasi.",
  },
  {
    judul: "Kenapa Mining Bitcoin Perlu Waktu 10 Menit?",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-07-11",
    link: "https://www.youtube.com/post/Ugkxt2Hfcroom3yQbgiT9gRzx6pzIOZP-onL",
    thumbnail: "https://drive.google.com/thumbnail?id=1V2v2XPRK205wO4rZ84MSks5vbQdMAQo4&sz=w400",
    deskripsi: "Bitcoin dirancang agar rata-rata hanya bisa memastikan 1 blok baru setiap 10 menit. Ini soal keamanan, kompetisi miner memecahkan teka-teki matematika, dan sistem penyesuaian tingkat kesulitan (difficulty adjustment) otomatis setiap 2.016 blok agar waktu blok tetap stabil.",
  },
  {
    judul: "Memahami Volatilitas Bitcoin: Sudut Pandang Keuangan Islam",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-12",
    link: "https://www.youtube.com/watch?v=wAdvnR8xfHw",
    thumbnail: "https://img.youtube.com/vi/wAdvnR8xfHw/hqdefault.jpg",
    deskripsi: "Pandangan volatilitas Bitcoin dari perspektif keuangan Islam — membahas hukum vs praktikalitas, Bitcoin sebagai komoditas, harga sebagai ketetapan Allah, perbandingan karakteristik aset, kebijaksanaan dalam anggaran, serta stabilitas fiat yang seringkali manipulatif.",
  },
  {
    judul: "Bitcoin & Inovasi: Memahami Landasan Hukum Islam",
    topik: "bitcoinphilosophy",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-05",
    link: "https://www.youtube.com/watch?v=x4eZ1_I7Cg8",
    thumbnail: "https://img.youtube.com/vi/x4eZ1_I7Cg8/hqdefault.jpg",
    deskripsi: "Prinsip-prinsip dasar fikih Islam dalam menilai inovasi teknologi baru — membahas niat vs realitas objek, analogi inovasi dalam teknologi, kaidah hukum asal inovasi, hukum asal duniawi adalah halal, beban pembuktian pada keharaman, serta kehati-hatian pribadi vs fatwa umum.",
  },
  {
    judul: "AI vs Sistem Keuangan",
    topik: "ai",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-13",
    link: "https://drive.google.com/file/d/1ZCi2RgreeoCqPsVDE4U-isRH01S_-LWE/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1ZCi2RgreeoCqPsVDE4U-isRH01S_-LWE&sz=w400",
    deskripsi: "Ilusi Uang yang Rusak — Kenapa Kita Sibuk Bicara Alat, Tapi Lupa Aturan Mainnya. Dokumen analitis tentang bagaimana AI dan sistem keuangan global saling berinteraksi, dan mengapa memahami sistem lebih penting dari sekadar menguasai alatnya.",
  },
  {
    judul: "Gradually, Then Suddenly",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-13",
    link: "https://drive.google.com/file/d/1tRwYWH6QR2yRqbDQEtp96qAH2zha71TK/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1tRwYWH6QR2yRqbDQEtp96qAH2zha71TK&sz=w400",
    deskripsi: "Memahami Bitcoin sebagai Uang — analisa first principles atas krisis sistem moneter, kepercayaan, dan masa depan uang yang jujur.",
  },
  {
    judul: "Broken Money",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-13",
    link: "https://drive.google.com/file/d/1x99T1z03LIBgwHXd3fXGhXkdL_0to1E5/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1x99T1z03LIBgwHXd3fXGhXkdL_0to1E5&sz=w400",
    deskripsi: "Bagaimana kegagalan sistem keuangan melahirkan uang baru — dari krisis menuju Genesis Block. Fix the money, fix the system.",
  },
  {
    judul: "Manifesto No. 001: Kita Tidak Butuh Lebih Banyak Teknologi, Kita Butuh Uang yang Lebih Baik",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-13",
    link: "https://drive.google.com/file/d/1czKBuIFwoxVJ5fyOChkbHMX-tdpka8HP/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1czKBuIFwoxVJ5fyOChkbHMX-tdpka8HP&sz=w400",
    deskripsi: "Sebuah manifesto Bitcoin yang mengutip Satoshi Nakamoto — Pseudonymous, Cypherpunk, Pencipta Bitcoin. Kita tidak butuh lebih banyak teknologi. Kita butuh uang yang lebih baik.",
  },
  {
    judul: "Satu Pelajaran Ekonomi: Cara Berpikir Seperti Ekonom Sejati",
    topik: "ekonomi",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-13",
    link: "https://www.youtube.com/watch?v=IOlU0H3BUCA",
    thumbnail: "https://img.youtube.com/vi/IOlU0H3BUCA/hqdefault.jpg",
    deskripsi: "Cara berpikir seperti ekonom sejati — memahami insentif sebagai kekuatan penggerak, melihat konsekuensi jangka pendek vs panjang, mengungkap kesalahan umum, hingga tokoh-tokoh penemu besar yang mengubah cara pandang ekonomi.",
  },
  {
    judul: "Kedaulatan Diri: Kekuatan dari Pengurangan",
    topik: "filsafat",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-13",
    link: "https://www.youtube.com/watch?v=WzDpM2XMmmU",
    thumbnail: "https://img.youtube.com/vi/WzDpM2XMmmU/hqdefault.jpg",
    deskripsi: "Ilusi ketergantungan sistem vs esensi kedaulatan sejati — kebebasan sejati bukan tentang menambah lebih banyak, melainkan tentang mengurangi ketergantungan pada sistem, pola kredit dan hutang, hingga menemukan kedaulatan yang tidak bisa diambil siapapun.",
  },
  {
    judul: "Kedaulatan Waktu: Siapa Pemilik Jam Kerja Anda?",
    topik: "filsafat",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-13",
    link: "https://www.youtube.com/watch?v=b9qvIcLiVaY",
    thumbnail: "https://img.youtube.com/vi/b9qvIcLiVaY/hqdefault.jpg",
    deskripsi: "Jebakan kesibukan (the time trap) vs strategi menuju kedaulatan waktu — membahas sikap bukalah, beli kembali waktu Anda, ikut produktivitas, pertukaran yang tulus, dan bagaimana dengan sistem yang tepat kamu bisa menjadi pemilik waktu sejati.",
  },
  {
    judul: "Solo, Pool, Hosting Mining & Site Farming",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-14",
    link: "https://drive.google.com/file/d/15l5VlJqFs-C5y6fWi-MBs18VrscE2YNB/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=15l5VlJqFs-C5y6fWi-MBs18VrscE2YNB&sz=w400",
    deskripsi: "Bukan harga. Bukan chart. Bukan trading. Bitcoin diproduksi — dari energi dan matematika. Edisi edukasi 2026 tentang mining dan produksi koin virgin.",
  },
  {
    judul: "Sisi Lain di Balik Layar: Virgin Bitcoin",
    topik: "bitcointechnicals",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-14",
    link: "https://drive.google.com/file/d/1Jmb0K91A4dK_cVBORdn0xfBQI6-_Fsh6/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1Jmb0K91A4dK_cVBORdn0xfBQI6-_Fsh6&sz=w400",
    deskripsi: "Bukan harga. Bukan chart. Bukan trading. Inilah pabrik tak kasat mata yang melahirkan Bitcoin: proses mining, produksi koin virgin, dan evolusi mesinnya. Mining · Solo · Pool · Hosting · ASIC.",
  },
  {
    judul: "Dari Energi Menjadi Bitcoin: Menambang Bukan Cuma Cari Bitcoin",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-14",
    link: "https://drive.google.com/file/d/13ZLbdKkqjA-PcSX5HKdVNYCC8lM91E03/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=13ZLbdKkqjA-PcSX5HKdVNYCC8lM91E03&sz=w400",
    deskripsi: "Mining = mengubah listrik menjadi uang digital. Energi + mesin + matematika = produksi Bitcoin. Mining menjaga jaringan tetap aman & terdesentralisasi — setiap blok = transaksi valid, jaringan aman = Bitcoin tetap berjalan. Bitcoin = nilai yang bebas & terbuka untuk kebebasan finansial semua orang.",
  },
  {
    judul: "Elastisitas Uang & Hiperbitcoinisasi",
    topik: "ekonomi",
    jenis: "Blog",
    kontributor: "Bitcoin SatoshiCat",
    tanggal: "2026-07-14",
    link: "https://elatisitasdanhiperbitcoinisasi.netlify.app/",
    thumbnail: "https://drive.google.com/thumbnail?id=1wlxU2pdYPMZV9Qt_OS3eXFZpZWGv6VUG&sz=w400",
    deskripsi: "Menger, Mises, dan Hayek sepakat: pasokan uang yang sehat harus bisa meregang mengikuti permintaan. Bagaimana gagasan itu berbenturan dengan mata uang berpasokan tetap seperti Bitcoin? Teori moneter Austria — bagian terapan.",
  },
  {
    judul: "Redenominasi Rupiah",
    topik: "ekonomi",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-16",
    link: "https://drive.google.com/file/d/1uQZx1_cvFr3mzPJswenTy0MXkmEt0zKj/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1uQZx1_cvFr3mzPJswenTy0MXkmEt0zKj&sz=w400",
    deskripsi: "Menghapus nol, bukan mengubah nilai. Analisa dampak bisnis, psikologi harga, dan sistem keuangan. Rp1.000 → Rp1, skala perubahan ÷ 1.000, nilai riil tetap, daya beli tidak berubah.",
  },
  {
    judul: "Kebohongan Tentang \"Nanti\": Mengapa Menunggu Adalah Jebakan",
    topik: "filsafat",
    jenis: "Video",
    kontributor: "hapdul",
    tanggal: "2026-07-16",
    link: "https://www.youtube.com/watch?v=kpVZzqlPKdI",
    thumbnail: "https://img.youtube.com/vi/kpVZzqlPKdI/hqdefault.jpg",
    deskripsi: "Bahaya tersembunyi dari menunda — perbedaan antara pemenang dan pecundang adalah keberanian untuk memulai hari ini. Day One vs One Day, ilusi modal yang tepat, someday adalah kebohongan terbesar, dan mengapa menunda sebelum tidur semakin berbahaya.",
  },
  {
    judul: "Dari Amarah Menjadi Aset",
    topik: "bitcoin",
    jenis: "PDF",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-17",
    link: "https://drive.google.com/file/d/1kUkBRBdFtGPVZrYSA0nlfq8mRo-LUyOT/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1kUkBRBdFtGPVZrYSA0nlfq8mRo-LUyOT&sz=w400",
    deskripsi: "Mengubah ideologi toxic maximalist menjadi nilai, pengalaman, dan aset nyata melalui semangat Cypherpunk & Bitcoin Manifesto. Bitcoin Only · Privacy is Normal · Code is Law · Bitcoin Fixes This.",
  },
  {
    judul: "Panduan Anti-Rugi Pemula: Rahasia Trading Nyaman & Cuan",
    topik: "technicalanalysis",
    jenis: "PDF",
    kontributor: "annasahmads",
    tanggal: "2026-07-17",
    link: "https://drive.google.com/file/d/1A_iv9dFhnNtfQCzEii-Eou-JbNvA9dr8/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1A_iv9dFhnNtfQCzEii-Eou-JbNvA9dr8&sz=w400",
    deskripsi: "Buku Saku Petualang Saham — panduan trading untuk pemula menggunakan sistem SVMT yang mudah dipahami orang awam.",
  },
  {
    judul: "Spektrum Bitcoin Maximalist: Mengubah \"Toxic\" Menjadi Aset Komunitas",
    topik: "bitcoin",
    jenis: "Infographic",
    kontributor: "Aryo Utomo",
    tanggal: "2026-07-17",
    link: "https://drive.google.com/file/d/1vfqbUlv7lCrsSq04zwSqJxHmebm6QGpe/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1vfqbUlv7lCrsSq04zwSqJxHmebm6QGpe&sz=w400",
    deskripsi: "Mengedukasi pengelola komunitas tentang cara mengidentifikasi tipe Bitcoin maximalist (Soft, Hardcore, Toxic) dan strategi praktis untuk mengarahkan energi mereka guna pertumbuhan ekosistem — melalui reframe & redirect energi, pemberian peran spesifik, sistem reward yang sehat, dan apresiasi pada argumentasi kuat yang sopan.",
  },
  {
    judul: "Content Creator Automation: Dari Riset Sampai Draft Konten",
    topik: "ai",
    jenis: "Infographic",
    kontributor: "annasahmads",
    tanggal: "2026-07-17",
    link: "https://drive.google.com/file/d/1Ba5g6FFGXjluNs-l-y0cANhC7onGv6di/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1Ba5g6FFGXjluNs-l-y0cANhC7onGv6di&sz=w400",
    deskripsi: "AI Agent mengotomasi workflow content creator tiap pagi — dari cari topik trending di Twitter/X dan Reddit, baca artikel, ringkas insight, generate ide konten + hook + angle, draft untuk Instagram/TikTok/YouTube/Blog, hingga kirim ke Telegram untuk review. Kamu tinggal review & posting.",
  },
  {
    judul: "How to Win with AI (Without Getting Replaced)",
    topik: "ai",
    jenis: "PDF",
    kontributor: "dhiemazalfa",
    tanggal: "2026-07-17",
    link: "https://drive.google.com/file/d/1X17TOd0c-dwQGW2n84sJGEmJOxXjOpfQ/view?usp=sharing",
    thumbnail: "https://drive.google.com/thumbnail?id=1X17TOd0c-dwQGW2n84sJGEmJOxXjOpfQ&sz=w400",
    deskripsi: "Panduan strategis menghadapi era AI — framework Give, Accelerate, Integrate, dan No AI untuk menentukan tugas mana yang diserahkan ke AI, dipercepat, diintegrasikan, atau tetap dikerjakan manusia agar tidak tergantikan.",
  },


];